version: 2

sources:
  - name: postgres
    schema: public
    tables:
      - name: os_places_dpa
      - name: os_places_lpi
      - name: england_wales_domestic_certificates
      - name: england_wales_non_domestic_certificates
      # - name: recommendations
