{{ config(materialized = 'table') }}

(
    SELECT
        rpc,
        postcode,
        logical_status_code,
        country_code_description,
        x_coordinate,
        last_update_date,
        classification_code_description,
        organisation_name,
        udprn,
        status,
        parent_uprn,
        postal_address_code,
        local_custodian_code_description,
        delivery_point_suffix,
        building_number,
        thoroughfare_name,
        "LANGUAGE" AS language,
        dependent_locality,
        blpu_state_code_description,
        blpu_state_code,
        local_custodian_code,
        blpu_state_date,
        dependent_thoroughfare_name,
        post_town,
        building_name,
        sub_building_name,
        postal_address_code_description,
        uprn,
        topography_layer_toid,
        address,
        y_coordinate,
        match_description,
        classification_code,
        entry_date,
        "MATCH" AS match,
        country_code,
        _airbyte_ab_id,
        _airbyte_emitted_at,
        _airbyte_normalized_at,
        _airbyte_os_places_dpa_hashid AS _airbyte_hashid,
        'DPA' AS os_api_source

    FROM {{ source('postgres', 'os_places_dpa') }}
)

UNION

(
    SELECT
        rpc,
        postcode_locator AS postcode,
        logical_status_code,
        country_code_description,
        x_coordinate,
        last_update_date,
        classification_code_description,
        'N/A' AS organisation_name,
        'N/A' AS udprn,
        status,
        parent_uprn,
        postal_address_code,
        local_custodian_code_description,
        'N/A' AS delivery_point_suffix,
        'N/A' AS building_number,
        'N/A' AS thoroughfare_name,
        "LANGUAGE" AS language,
        'N/A' AS dependent_locality,
        blpu_state_code_description,
        blpu_state_code,
        local_custodian_code,
        blpu_state_date,
        'N/A' AS dependent_thoroughfare_name,
        'N/A' AS post_town,
        'N/A' AS building_name,
        'N/A' AS sub_building_name,
        postal_address_code_description,
        uprn,
        topography_layer_toid,
        address,
        y_coordinate,
        match_description,
        classification_code,
        entry_date,
        "MATCH" AS match,
        country_code,
        _airbyte_ab_id,
        _airbyte_emitted_at,
        _airbyte_normalized_at,
        _airbyte_os_places_lpi_hashid AS _airbyte_hashid,
        'LPI' AS os_api_source

    FROM {{ source('postgres', 'os_places_lpi') }}
    WHERE classification_code_description NOT IN (
        'Street Record',
        'Property Shell',
        'Static Water',
        'Electricity Sub-Station',
        'Postal Box',
        'Bus Shelter',
        'Additional Mail / Packet Addressee',
        'Hopper / Silo / Cistern / Tank',
        'General Storage Land',
        'Telecommunication',
        'House Boat',
        'Equestrian',
        'Telephone Box',
        'PO Box',
        'Advertising Hoarding',
        'Allocated Parking'
    )
)
