{{ config(materialized = 'table') }}
SELECT
    CAST("walls_env_eff" AS TEXT) AS walls_env_eff,
    CAST(NULLIF("fixed_lighting_outlets_count", '') AS FLOAT) AS fixed_lighting_outlets_count,
    COALESCE(NULLIF(CAST("glazed_area" AS TEXT), ''), 'NO DATA!') AS glazed_area,
    CAST(NULLIF("energy_consumption_potential", '') AS FLOAT) AS energy_consumption_potential,
    CAST(NULLIF("low_energy_fixed_light_count", '') AS FLOAT) AS low_energy_fixed_light_count,
    CAST("secondheat_description" AS TEXT) AS secondheat_description,
    CAST("lmk_key" AS TEXT) AS lmk_key,
    CAST(county AS TEXT) AS county,
    CAST("main_fuel" AS TEXT) AS main_fuel,
    CAST("mains_gas_flag" AS TEXT) AS mains_gas_flag,
    CAST(NULLIF("number_open_fireplaces", '') AS INT) AS number_open_fireplaces,
    CAST("co2_emissions_potential" AS FLOAT) AS co2_emissions_potential,
    CAST(NULLIF("current_energy_efficiency", '') AS FLOAT) AS current_energy_efficiency,
    CAST("walls_energy_eff" AS TEXT) AS walls_energy_eff,
    CAST(NULLIF("number_heated_rooms", '') AS INT) AS number_heated_rooms,
    CAST("floor_env_eff" AS TEXT) AS floor_env_eff,
    CAST("mechanical_ventilation" AS TEXT) AS mechanical_ventilation,
    CAST(NULLIF("photo_supply", '') AS FLOAT) AS photo_supply,
    CAST("mainheat_env_eff" AS TEXT) AS mainheat_env_eff,
    CAST(NULLIF("environment_impact_potential", '') AS FLOAT) AS environment_impact_potential,
    CAST("windows_energy_eff" AS TEXT) AS windows_energy_eff,
    CAST("roof_env_eff" AS TEXT) AS roof_env_eff,
    CAST("total_floor_area" AS FLOAT) AS total_floor_area,
    CAST("flat_top_storey" AS TEXT) AS flat_top_storey,
    CAST(NULLIF("multi_glaze_proportion", '') AS FLOAT) AS multi_glaze_proportion,
    CAST(tenure AS TEXT) AS tenure,
    CAST(posttown AS TEXT) AS posttown,
    CAST(uprn AS TEXT) AS uprn,
    CAST("mainheat_energy_eff" AS TEXT) AS mainheat_energy_eff,
    CAST("current_energy_rating" AS TEXT) AS current_energy_rating,
    CAST(postcode AS TEXT) AS postcode,
    CAST("mainheat_description" AS TEXT) AS mainheat_description,
    CAST("sheating_env_eff" AS TEXT) AS sheating_env_eff,
    CAST("walls_description" AS TEXT) AS walls_description,
    CAST(NULLIF("flat_storey_count", '') AS FLOAT) AS flat_storey_count,
    CAST("potential_energy_rating" AS TEXT) AS potential_energy_rating,
    CAST("hotwater_description" AS TEXT) AS hotwater_description,
    CAST(NULLIF("lighting_cost_current", '') AS FLOAT) AS lighting_cost_current,
    CAST(NULLIF("floor_height", '') AS FLOAT) AS floor_height,
    CAST(NULLIF("lighting_cost_potential", '') AS FLOAT) AS lighting_cost_potential,
    CAST("floor_energy_eff" AS TEXT) AS floor_energy_eff,
    CAST("windows_description" AS TEXT) AS windows_description,
    CAST("sheating_energy_eff" AS TEXT) AS sheating_energy_eff,
    CAST("energy_consumption_current" AS FLOAT) AS energy_consumption_current,
    CAST("potential_energy_efficiency" AS FLOAT) AS potential_energy_efficiency,
    CAST(NULLIF("heating_cost_current", '') AS FLOAT) AS heating_cost_current,
    CAST(NULLIF("hot_water_cost_current", '') AS FLOAT) AS hot_water_cost_current,
    CAST("construction_age_band" AS TEXT) AS construction_age_band,
    CAST("main_heating_controls" AS TEXT) AS main_heating_controls,
    CAST("solar_water_heating_flag" AS TEXT) AS solar_water_heating_flag,
    CAST("built_form" AS TEXT) AS built_form,
    CAST("property_type" AS TEXT) AS property_type,
    CAST(NULLIF("co2_emiss_curr_per_floor_area", '') AS FLOAT) AS co2_emiss_curr_per_floor_area,
    CAST("roof_energy_eff" AS TEXT) AS roof_energy_eff,
    CAST("lighting_env_eff" AS TEXT) AS lighting_env_eff,
    CAST(NULLIF("extension_count", '') AS FLOAT) AS extension_count,
    CAST("floor_level" AS TEXT) AS floor_level,
    CAST("lodgement_datetime" AS TEXT) AS lodgement_datetime,
    CAST("heat_loss_corridor" AS TEXT) AS heat_loss_corridor,
    CAST("mainheatc_env_eff" AS TEXT) AS mainheatc_env_eff,
    CAST("lighting_description" AS TEXT) AS lighting_description,
    CAST("windows_env_eff" AS TEXT) AS windows_env_eff,
    CAST("hot_water_energy_eff" AS TEXT) AS hot_water_energy_eff,
    CAST("transaction_type" AS TEXT) AS transaction_type,
    CAST("mainheatc_energy_eff" AS TEXT) AS mainheatc_energy_eff,
    CAST(NULLIF("co2_emissions_current", '') AS FLOAT) AS co2_emissions_current,
    CAST("local_authority_label" AS TEXT) AS local_authority_label,
    CAST(address AS TEXT) AS address,
    CAST(address1 AS TEXT) AS address1,
    CAST(address2 AS TEXT) AS address2,
    CAST(address3 AS TEXT) AS address3,
    CAST("roof_description" AS TEXT) AS roof_description,
    CAST("hot_water_env_eff" AS TEXT) AS hot_water_env_eff,
    CAST(NULLIF("environment_impact_current", '') AS FLOAT) AS environment_impact_current,
    CAST("energy_tariff" AS TEXT) AS energy_tariff,
    CAST(NULLIF("hot_water_cost_potential", '') AS FLOAT) AS hot_water_cost_potential,
    CAST("glazed_type" AS TEXT) AS glazed_type,
    CAST("lighting_energy_eff" AS TEXT) AS lighting_energy_eff,
    CAST(NULLIF("heating_cost_potential", '') AS FLOAT) AS heating_cost_potential,
    CAST("local_authority" AS TEXT) AS local_authority,
    CAST("constituency_label" AS TEXT) AS constituency_label,
    CAST("mainheatcont_description" AS TEXT) AS mainheatcont_description,
    CAST("building_reference_number" AS TEXT) AS building_reference_number,
    CAST(NULLIF("low_energy_lighting", '') AS INT) AS low_energy_lighting,
    CAST(NULLIF("unheated_corridor_length", '') AS FLOAT) AS unheated_corridor_length,
    CAST(constituency AS TEXT) AS constituency,
    CAST("floor_description" AS TEXT) AS floor_description,
    CAST(NULLIF("wind_turbine_count", '') AS INT) AS wind_turbine_count,
    CAST("inspection_date" AS DATE) AS inspection_date,
    CAST("uprn_source" AS TEXT) AS uprn_source,
    CAST("lodgement_date" AS DATE) AS lodgement_date,
    CAST(NULLIF("number_habitable_rooms", '') AS INT) AS number_habitable_rooms,
    _airbyte_raw_id,
    _airbyte_extracted_at,
    _airbyte_generation_id,
    _airbyte_meta,
    'domestic' AS certificate_type
FROM
    {{ source('postgres', 'england_wales_domestic_certificates') }}

UNION

SELECT
    CAST(NULL AS TEXT) AS walls_env_eff,
    CAST(NULL AS FLOAT) AS fixed_lighting_outlets_count,
    CAST('NO DATA!' AS TEXT) AS glazed_area,
    CAST(NULL AS FLOAT) AS energy_consumption_potential,
    CAST(NULL AS FLOAT) AS low_energy_fixed_light_count,
    CAST(NULL AS TEXT) AS secondheat_description,
    CAST("lmk_key" AS TEXT) AS lmk_key,
    CAST(county AS TEXT) AS county,
    CAST(NULL AS TEXT) AS main_fuel,
    CAST(NULL AS TEXT) AS mains_gas_flag,
    CAST(NULL AS INT) AS number_open_fireplaces,
    CAST(NULL AS FLOAT) AS co2_emissions_potential,
    CAST(NULL AS FLOAT) AS current_energy_efficiency,
    CAST(NULL AS TEXT) AS walls_energy_eff,
    CAST(NULL AS INT) AS number_heated_rooms,
    CAST(NULL AS TEXT) AS floor_env_eff,
    CAST(NULL AS TEXT) AS mechanical_ventilation,
    CAST(NULL AS FLOAT) AS photo_supply,
    CAST(NULL AS TEXT) AS mainheat_env_eff,
    CAST(NULL AS FLOAT) AS environment_impact_potential,
    CAST(NULL AS TEXT) AS windows_energy_eff,
    CAST(NULL AS TEXT) AS roof_env_eff,
    CAST(NULL AS FLOAT) AS total_floor_area,
    CAST(NULL AS TEXT) AS flat_top_storey,
    CAST(NULL AS FLOAT) AS multi_glaze_proportion,
    CAST(NULL AS TEXT) AS tenure,
    CAST(posttown AS TEXT) AS posttown,
    CAST(uprn AS TEXT) AS uprn,
    CAST(NULL AS TEXT) AS mainheat_energy_eff,
    CAST(NULL AS TEXT) AS current_energy_rating,
    CAST(postcode AS TEXT) AS postcode,
    CAST(NULL AS TEXT) AS mainheat_description,
    CAST(NULL AS TEXT) AS sheating_env_eff,
    CAST(NULL AS TEXT) AS walls_description,
    CAST(NULL AS FLOAT) AS flat_storey_count,
    CAST(NULL AS TEXT) AS potential_energy_rating,
    CAST(NULL AS TEXT) AS hotwater_description,
    CAST(NULL AS FLOAT) AS lighting_cost_current,
    CAST(NULL AS FLOAT) AS floor_height,
    CAST(NULL AS FLOAT) AS lighting_cost_potential,
    CAST(NULL AS TEXT) AS floor_energy_eff,
    CAST(NULL AS TEXT) AS windows_description,
    CAST(NULL AS TEXT) AS sheating_energy_eff,
    CAST(NULL AS FLOAT) AS energy_consumption_current,
    CAST(NULL AS FLOAT) AS potential_energy_efficiency,
    CAST(NULL AS FLOAT) AS heating_cost_current,
    CAST(NULL AS FLOAT) AS hot_water_cost_current,
    CAST(NULL AS TEXT) AS construction_age_band,
    CAST(NULL AS TEXT) AS main_heating_controls,
    CAST(NULL AS TEXT) AS solar_water_heating_flag,
    CAST(NULL AS TEXT) AS built_form,
    CAST("property_type" AS TEXT) AS property_type,
    CAST(NULL AS FLOAT) AS co2_emiss_curr_per_floor_area,
    CAST(NULL AS TEXT) AS roof_energy_eff,
    CAST(NULL AS TEXT) AS lighting_env_eff,
    CAST(NULL AS FLOAT) AS extension_count,
    CAST(NULL AS TEXT) AS floor_level,
    CAST("lodgement_datetime" AS TEXT) AS lodgement_datetime,
    CAST(NULL AS TEXT) AS heat_loss_corridor,
    CAST(NULL AS TEXT) AS mainheatc_env_eff,
    CAST(NULL AS TEXT) AS lighting_description,
    CAST(NULL AS TEXT) AS windows_env_eff,
    CAST(NULL AS TEXT) AS hot_water_energy_eff,
    CAST("transaction_type" AS TEXT) AS transaction_type,
    CAST(NULL AS TEXT) AS mainheatc_energy_eff,
    CAST(NULL AS FLOAT) AS co2_emissions_current,
    CAST("local_authority_label" AS TEXT) AS local_authority_label,
    CAST(address AS TEXT) AS address,
    CAST(address1 AS TEXT) AS address1,
    CAST(address2 AS TEXT) AS address2,
    CAST(address3 AS TEXT) AS address3,
    CAST(NULL AS TEXT) AS roof_description,
    CAST(NULL AS TEXT) AS hot_water_env_eff,
    CAST(NULL AS FLOAT) AS environment_impact_current,
    CAST(NULL AS TEXT) AS energy_tariff,
    CAST(NULL AS FLOAT) AS hot_water_cost_potential,
    CAST(NULL AS TEXT) AS glazed_type,
    CAST(NULL AS TEXT) AS lighting_energy_eff,
    CAST(NULL AS FLOAT) AS heating_cost_potential,
    CAST("local_authority" AS TEXT) AS local_authority,
    CAST("constituency_label" AS TEXT) AS constituency_label,
    CAST(NULL AS TEXT) AS mainheatcont_description,
    CAST("building_reference_number" AS TEXT) AS building_reference_number,
    CAST(NULL AS INT) AS low_energy_lighting,
    CAST(NULL AS FLOAT) AS unheated_corridor_length,
    CAST(constituency AS TEXT) AS constituency,
    CAST(NULL AS TEXT) AS floor_description,
    CAST(NULL AS INT) AS wind_turbine_count,
    CAST("inspection_date" AS DATE) AS inspection_date,
    CAST("uprn_source" AS TEXT) AS uprn_source,
    CAST("lodgement_date" AS DATE) AS lodgement_date,
    CAST(NULL AS INT) AS number_habitable_rooms,
    _airbyte_raw_id,
    _airbyte_extracted_at,
    _airbyte_generation_id,
    _airbyte_meta,
    'non_domestic' AS certificate_type
FROM
    {{ source('postgres', 'england_wales_non_domestic_certificates') }}
