"""Copyright (c) 2023 Airbyte, Inc., all rights reserved."""

import json
from collections.abc import Generator
from datetime import datetime
from time import sleep

import numpy as np
import requests
from airbyte_cdk.logger import AirbyteLogger
from airbyte_cdk.models import (
    AirbyteCatalog,
    AirbyteConnectionStatus,
    AirbyteMessage,
    AirbyteRecordMessage,
    AirbyteStream,
    ConfiguredAirbyteCatalog,
    Status,
    Type,
)
from airbyte_cdk.sources import Source
from requests.adapters import HTTPAdapter, Retry

from . import utils


class SourceEpcRecommendations(Source):
    def check(self, logger: AirbyteLogger, config: json) -> AirbyteConnectionStatus:
        """Tests if the input configuration can be used to successfully connect to the integration.

        :param logger: Logging object to display debug/info/error to the logs (logs will not be
            accessible via airbyte UI if they are not passed to this logger)
        :param config: Json object containing the configuration of this source, content of this json
            is as specified in the properties of the spec.yaml file

        :return: AirbyteConnectionStatus indicating a Success or Failure
        """
        try:
            headers = {
                "Accept": "application/zip",
                "Authorization": config["auth_key"],
            }

            s = requests.Session()
            retries = Retry(
                total=10,
                backoff_factor=1,
                status_forcelist=[429, 500, 502, 503, 504],
            )
            s.mount("http://", HTTPAdapter(max_retries=retries))
            s.mount("https://", HTTPAdapter(max_retries=retries))

            response = s.get(
                "https://epc.opendatacommunities.org/api/v1/domestic/search",
                headers=headers,
                timeout=500,
            )
            sleep(1)
            if response.status_code == 200:
                return AirbyteConnectionStatus(status=Status.SUCCEEDED)

            return AirbyteConnectionStatus(
                status=Status.FAILED,
                message=f"Authorization failed with status {response.status_code}",
            )
        except Exception as e:  # pylint: disable=invalid-name disable=broad-exception-caught
            return AirbyteConnectionStatus(
                status=Status.FAILED,
                message=f"An exception occurred: {e!s}",
            )

    def discover(self, logger: AirbyteLogger, config: json) -> AirbyteCatalog:
        """Returns an AirbyteCatalog representing the available streams and fields in this
        integration.

        For example, given valid credentials to a Postgres database, returns an Airbyte catalog
        where each postgres table is a stream, and each table column is a field.

        :param logger: Logging object to display debug/info/error to the logs (logs will not be
            accessible via airbyte UI if they are not passed to this logger)
        :param config: Json object containing the configuration of this source, content of this json
            is as specified in
        the properties of the spec.yaml file

        :return: AirbyteCatalog is an object describing a list of all available streams in this
            source. A stream is an AirbyteStream object that includes: - its stream name (or table
            name in the case of Postgres) - json_schema providing the specifications of expected
            schema for this stream (a list of columns described by their names and types)
        """
        streams = []

        stream_name = "recommendations"
        json_schema = {
            "$schema": "http://json-schema.org/draft-07/schema#",
            "type": "object",
            "required": ["auth_key", "start_year", "end_year"],
            "properties": {
                "LMK_KEY": {"type": "string"},
                "IMPROVEMENT_ITEM": {"type": "number"},
                "IMPROVEMENT_SUMMARY_TEXT": {"type": ["null", "string"]},
                "IMPROVEMENT_DESCR_TEXT": {"type": ["null", "string"]},
                "IMPROVEMENT_ID": {"type": ["null", "number"]},
                "IMPROVEMENT_ID_TEXT": {"type": ["null", "string"]},
                "INDICATIVE_COST": {"type": ["null", "string"]},
            },
        }

        streams.append(
            AirbyteStream(
                name=stream_name,
                json_schema=json_schema,
                supported_sync_modes=["full_refresh"],
            ),
        )
        return AirbyteCatalog(streams=streams)

    def read(
        self,
        logger: AirbyteLogger,
        config: json,
        catalog: ConfiguredAirbyteCatalog,
        state: dict[str, any],
    ) -> Generator[AirbyteMessage, None, None]:
        """Returns a generator of the AirbyteMessages generated by reading the source with the given
        configuration, catalog, and state.

        :param logger: Logging object to display debug/info/error to the logs (logs will not be
            accessible via airbyte UI if they are not passed to this logger)
        :param config: Json object containing the configuration of this source, content of this json
            is as specified in the properties of the spec.yaml file
        :param catalog: The input catalog is a ConfiguredAirbyteCatalog which is almost the same as
            AirbyteCatalog returned by discover(), but in addition, it's been configured in the UI!

        For each particular stream and field, there may have been provided with extra modifications
        such as: filtering streams and/or columns out, renaming some entities, etc :param state:

        When a Airbyte reads data from a source, it might need to keep a checkpoint cursor to resume
        replication in the future from that saved checkpoint. This is the object that is provided
        with state from previous runs and avoid replicating the entire set of data every time.

        :return: A generator that produces a stream of AirbyteRecordMessage contained in
            AirbyteMessage object.
        """
        logger.info(f"Initializing EPC Recommendations extraction with {config=}")

        stream_name = "recommendations"
        df = (
            utils.main(
                local_authority_list=config["local_authority_list"].split(","),
                start_year=config["start_year"],
                end_year=config["end_year"],
                auth_key=config["auth_key"],
                logger=logger,
            )
            .replace({np.nan: None})
            .to_dict(orient="records")
        )

        logger.info(f"Yielding {len(df)} AirbyteMessage records")
        for row in df:
            yield AirbyteMessage(
                type=Type.RECORD,
                record=AirbyteRecordMessage(
                    stream=stream_name,
                    data=row,
                    emitted_at=int(datetime.now().timestamp()) * 1000,
                ),
            )
