version: 2

sources:
  - name: postgres
    schema: "{{ env_var('DB_SCHEMA') }}"
    tables:
      # - name: os_places_dpa
      # - name: os_places_lpi
      - name: certificates
      # - name: england_wales_non_domestic_certificates
      # - name: os_ngd_buildings_east_mids
      # - name: recommendations
