{{ config(materialized = 'table') }}
(
    SELECT
        address,
        address1,
        address2,
        address3,
        CAST(NULL AS TEXT) AS asset_rating,
        CAST(NULL AS TEXT) AS asset_rating_band,
        CAST(NULL AS TEXT) AS aircon_present,
        CAST(NULL AS INT) AS ac_inspection_commissioned,
        CAST(NULL AS TEXT) AS aircon_kw_rating,
        CAST("building-reference-number" AS BIGINT) AS building_reference_number,
        CAST(NULL AS TEXT) AS building_level,
        CAST(NULL AS FLOAT) AS building_emissions,
        CAST(NULL AS TEXT) AS building_environment,
        "built-form" AS built_form,
        CAST("co2-emiss-curr-per-floor-area" AS FLOAT) AS co2_emiss_curr_per_floor_area,
        CAST("co2-emissions-current" AS FLOAT) AS co2_emissions_current,
        CAST("co2-emissions-potential" AS FLOAT) AS co2_emissions_potential,
        constituency,
        "constituency-label" AS constituency_label,
        "construction-age-band" AS construction_age_band,
        county,
        CAST("current-energy-efficiency" AS INT) AS current_energy_efficiency,
        "current-energy-rating" AS current_energy_rating,
        CAST(NULL AS FLOAT) AS estimated_aircon_kw_rating,
        CAST(
            NULLIF("energy-consumption-current", '') AS DOUBLE PRECISION
        ) AS energy_consumption_current,
        CAST(
            NULLIF("energy-consumption-potential", '') AS DOUBLE PRECISION
        ) AS energy_consumption_potential,
        "energy-tariff" AS energy_tariff,
        CAST("environment-impact-current" AS FLOAT) AS environment_impact_current,
        CAST("environment-impact-potential" AS BIGINT) AS environment_impact_potential,
        CAST(NULLIF("extension-count", '') AS FLOAT) AS extension_count,
        CAST(NULL AS INT) AS existing_stock_benchmark,
        CAST(NULLIF("fixed-lighting-outlets-count", '') AS INT) AS fixed_lighting_outlets_count,
        CAST(NULLIF("flat-storey-count", '') AS FLOAT) AS flat_storey_count,
        "flat-top-storey" AS flat_top_storey,
        "floor-description" AS floor_description,
        "floor-energy-eff" AS floor_energy_eff,
        "floor-env-eff" AS floor_env_eff,
        CAST(NULLIF("floor-height", '') AS DOUBLE PRECISION) AS floor_height,
        "floor-level" AS floor_level,
        CAST(NULL AS FLOAT) AS floor_area,
        "glazed-area" AS glazed_area,
        "glazed-type" AS glazed_type,
        "heat-loss-corridor" AS heat_loss_corridor,
        CAST(NULLIF("heating-cost-current", '') AS FLOAT) AS heating_cost_current,
        CAST(NULLIF("heating-cost-potential", '') AS FLOAT) AS heating_cost_potential,
        CAST(NULLIF("hot-water-cost-current", '') AS FLOAT) AS hot_water_cost_current,
        CAST(NULLIF("hot-water-cost-potential", '') AS FLOAT) AS hot_water_cost_potential,
        CAST(NULLIF("hot-water-energy-eff", '') AS TEXT) AS hot_water_energy_eff,
        CAST(NULLIF("hot-water-env-eff", '') AS TEXT) AS hot_water_env_eff,
        CAST(NULLIF("hotwater-description", '') AS TEXT) AS hotwater_description,
        TO_DATE("inspection-date", 'YYYY-MM-DD') AS inspection_date,
        CAST(NULLIF("lighting-cost-current", '') AS FLOAT) AS lighting_cost_current,
        CAST(NULLIF("lighting-cost-potential", '') AS FLOAT) AS lighting_cost_potential,
        "lighting-description" AS lighting_description,
        "lighting-energy-eff" AS lighting_energy_eff,
        "lighting-env-eff" AS lighting_env_eff,
        "lmk-key" AS lmk_key,
        "local-authority" AS local_authority,
        "local-authority-label" AS local_authority_label,
        TO_DATE("lodgement-date", 'YYYY-MM-DD') AS lodgement_date,
        "lodgement-datetime" AS lodgement_datetime,
        CAST(NULLIF("low-energy-fixed-light-count", '') AS FLOAT) AS low_energy_fixed_light_count,
        CAST(NULLIF("low-energy-lighting", '') AS FLOAT) AS low_energy_lighting,
        "main-fuel" AS main_fuel,
        "main-heating-controls" AS main_heating_controls,
        "mainheat-description" AS mainheat_description,
        "mainheat-energy-eff" AS mainheat_energy_eff,
        "mainheat-env-eff" AS mainheat_env_eff,
        "mainheatc-energy-eff" AS mainheatc_energy_eff,
        "mainheatc-env-eff" AS mainheatc_env_eff,
        "mainheatcont-description" AS mainheatcont_description,
        "mains-gas-flag" AS mains_gas_flag,
        "mechanical-ventilation" AS mechanical_ventilation,
        "multi-glaze-proportion" AS multi_glaze_proportion,
        CAST(NULL AS INT) AS new_build_benchmark,
        CAST(NULLIF("number-habitable-rooms", '') AS INT) AS number_habitable_rooms,
        CAST(NULLIF("number-heated-rooms", '') AS INT) AS number_heated_rooms,
        CAST(NULLIF("number-open-fireplaces", '') AS INT) AS number_open_fireplaces,
        CAST(NULL AS TEXT) AS other_fuel_desc,
        CAST(NULL AS INT) AS primary_energy_value,
        "photo-supply" AS photo_supply,
        postcode,
        posttown,
        "potential-energy-efficiency" AS potential_energy_efficiency,
        "potential-energy-rating" AS potential_energy_rating,
        "property-type" AS property_type,
        CAST(NULL AS TEXT) AS renewable_sources,
        "roof-description" AS roof_description,
        "roof-energy-eff" AS roof_energy_eff,
        "roof-env-eff" AS roof_env_eff,
        "secondheat-description" AS secondheat_description,
        "sheating-energy-eff" AS sheating_energy_eff,
        "sheating-env-eff" AS sheating_env_eff,
        "solar-water-heating-flag" AS solar_water_heating_flag,
        CAST(NULL AS TEXT) AS special_energy_uses,
        CAST(NULL AS FLOAT) AS standard_emissions,
        CAST(NULL AS FLOAT) AS target_emissions,
        tenure,
        CAST("total-floor-area" AS TEXT) AS total_floor_area,
        "transaction-type" AS transaction_type,
        CAST(NULL AS FLOAT) AS typical_emissions,
        CAST(NULLIF("unheated-corridor-length", '') AS FLOAT) AS unheated_corridor_length,
        CAST(NULLIF(uprn, '') AS BIGINT) AS uprn,
        "uprn-source" AS uprn_source,
        "walls-description" AS walls_description,
        "walls-energy-eff" AS walls_energy_eff,
        "walls-env-eff" AS walls_env_eff,
        CAST(NULLIF("wind-turbine-count", '') AS INT) AS wind_turbine_count,
        "windows-description" AS windows_description,
        "windows-energy-eff" AS windows_energy_eff,
        "windows-env-eff" AS windows_env_eff
    FROM {{ source('postgres', 'wales_domestic_certificates') }}
)

UNION

(
    SELECT
        address,
        address1,
        address2,
        address3,
        CAST(asset_rating AS TEXT) AS asset_rating,
        asset_rating_band,
        aircon_present,
        CAST(NULLIF(ac_inspection_commissioned, '') AS INT) AS ac_inspection_commissioned,
        aircon_kw_rating,
        CAST(NULLIF(building_reference_number, '') AS BIGINT) AS building_refererence_number,
        building_level,
        CAST(NULLIF(building_emissions, '') AS DOUBLE PRECISION) AS building_emissions,
        building_environment,
        CAST(NULL AS TEXT) AS built_form,
        CAST(NULL AS FLOAT) AS co2_emiss_curr_per_floor_area,
        CAST(NULL AS FLOAT) AS co2_emissions_current,
        CAST(NULL AS FLOAT) AS co2_emissions_potential,
        constituency,
        CAST(NULL AS TEXT) AS constituency_label,
        CAST(NULL AS TEXT) AS construction_age_band,
        county,
        CAST(NULL AS INT) AS current_energy_efficiency,
        CAST(NULL AS TEXT) AS current_energy_rating,
        CAST(
            NULLIF(estimated_aircon_kw_rating, '') AS DOUBLE PRECISION
        ) AS estimated_aircon_kw_rating,
        CAST(NULL AS BIGINT) AS energy_consumption_current,
        CAST(NULL AS BIGINT) AS energy_consumption_potential,
        CAST(NULL AS TEXT) AS energy_tariff,
        CAST(NULL AS FLOAT) AS environment_impact_current,
        CAST(NULL AS BIGINT) AS environment_impact_potential,
        CAST(NULL AS FLOAT) AS extension_count,
        CAST(existing_stock_benchmark AS INT) AS existing_stock_benchmark,
        CAST(NULL AS INT) AS fixed_lighting_outlets_count,
        CAST(NULL AS FLOAT) AS flat_storey_count,
        CAST(NULL AS TEXT) AS flat_top_storey,
        CAST(NULL AS TEXT) AS floor_description,
        CAST(NULL AS TEXT) AS floor_energy_eff,
        CAST(NULL AS TEXT) AS floor_env_eff,
        CAST(NULL AS FLOAT) AS floor_height,
        CAST(NULL AS TEXT) AS floor_level,
        CAST(NULLIF(floor_area, '') AS DOUBLE PRECISION) AS floor_area,
        CAST(NULL AS TEXT) AS glazed_area,
        CAST(NULL AS TEXT) AS glazed_type,
        CAST(NULL AS TEXT) AS heat_loss_corridor,
        CAST(NULL AS FLOAT) AS heating_cost_current,
        CAST(NULL AS FLOAT) AS heating_cost_potential,
        CAST(NULL AS FLOAT) AS hot_water_cost_current,
        CAST(NULL AS FLOAT) AS hot_water_cost_potential,
        CAST(NULL AS TEXT) AS hot_water_energy_eff,
        CAST(NULL AS TEXT) AS hot_water_env_eff,
        CAST(NULL AS TEXT) AS hotwater_description,
        TO_DATE(inspection_date, 'YYYY_MM_DD') AS inspection_date,
        CAST(NULL AS FLOAT) AS lighting_cost_current,
        CAST(NULL AS FLOAT) AS lighting_cost_potential,
        CAST(NULL AS TEXT) AS lighting_description,
        CAST(NULL AS TEXT) AS lighting_energy_eff,
        CAST(NULL AS TEXT) AS lighting_env_eff,
        lmk_key,
        local_authority,
        local_authority_label,
        TO_DATE(lodgement_date, 'YYYY_MM_DD') AS lodgement_date,
        lodgement_datetime,
        CAST(NULL AS FLOAT) AS low_energy_fixed_light_count,
        CAST(NULL AS FLOAT) AS low_energy_lighting,
        main_heating_fuel AS main_fuel,
        CAST(NULL AS TEXT) AS main_heating_controls,
        CAST(NULL AS TEXT) AS mainheat_description,
        CAST(NULL AS TEXT) AS mainheat_energy_eff,
        CAST(NULL AS TEXT) AS mainheat_env_eff,
        CAST(NULL AS TEXT) AS mainheatc_energy_eff,
        CAST(NULL AS TEXT) AS mainheatc_env_eff,
        CAST(NULL AS TEXT) AS mainheatcont_description,
        CAST(NULL AS TEXT) AS mains_gas_flag,
        CAST(NULL AS TEXT) AS mechanical_ventilation,
        CAST(NULL AS TEXT) AS multi_glaze_proportion,
        CAST(new_build_benchmark AS INT) AS new_build_benchmark,
        CAST(NULL AS INT) AS number_habitable_rooms,
        CAST(NULL AS INT) AS number_heated_rooms,
        CAST(NULL AS INT) AS number_open_fireplaces,
        other_fuel_desc,
        CAST(NULLIF(primary_energy_value, '') AS INT) AS primary_energy_value,
        CAST(NULL AS TEXT) AS photo_supply,
        postcode,
        posttown,
        CAST(NULL AS TEXT) AS potential_energy_efficiency,
        CAST(NULL AS TEXT) AS potential_energy_rating,
        property_type,
        renewable_sources,
        CAST(NULL AS TEXT) AS roof_description,
        CAST(NULL AS TEXT) AS roof_energy_eff,
        CAST(NULL AS TEXT) AS roof_env_eff,
        CAST(NULL AS TEXT) AS secondheat_description,
        CAST(NULL AS TEXT) AS sheating_energy_eff,
        CAST(NULL AS TEXT) AS sheating_env_eff,
        CAST(NULL AS TEXT) AS solar_water_heating_flag,
        special_energy_uses,
        CAST(NULLIF(standard_emissions, '') AS DOUBLE PRECISION) AS standard_emissions,
        CAST(NULLIF(target_emissions, '') AS DOUBLE PRECISION) AS target_emissions,
        CAST(NULL AS TEXT) AS tenure,
        CAST(NULL AS TEXT) AS total_floor_area,
        transaction_type,
        CAST(NULLIF(typical_emissions, '') AS DOUBLE PRECISION) AS typical_emissions,
        CAST(NULL AS FLOAT) AS unheated_corridor_length,
        CAST(NULLIF(uprn, '') AS BIGINT) AS uprn,
        uprn_source,
        CAST(NULL AS TEXT) AS walls_description,
        CAST(NULL AS TEXT) AS walls_energy_eff,
        CAST(NULL AS TEXT) AS walls_env_eff,
        CAST(NULL AS INT) AS wind_turbine_count,
        CAST(NULL AS TEXT) AS windows_description,
        CAST(NULL AS TEXT) AS windows_energy_eff,
        CAST(NULL AS TEXT) AS windows_env_eff
    FROM {{ source('postgres', 'wales_nondomestic_certificates') }}

)

UNION

(
    SELECT
        address,
        address1,
        address2,
        address3,
        CAST(NULL AS TEXT) AS asset_rating,
        "asset-rating-band" AS asset_rating_band,
        "aircon-present" AS aircon_present,
        CAST(
            NULLIF("ac-inspection-commissioned", '') AS INT
        ) AS ac_inspection_commissioned,
        "aircon-kw-rating" AS aircon_kw_rating,
        CAST("building-reference-number" AS BIGINT) AS building_refererence_number,
        "building-level" AS building_level,
        CAST(
            NULLIF("building-emissions", '') AS DOUBLE PRECISION
        ) AS building_emissions,
        "building-environment" AS building_environment,
        CAST(NULL AS TEXT) AS built_form,
        CAST(NULL AS FLOAT) AS co2_emiss_curr_per_floor_area,
        CAST(NULL AS FLOAT) AS co2_emissions_current,
        CAST(NULL AS FLOAT) AS co2_emissions_potential,
        constituency,
        CAST(NULL AS TEXT) AS constituency_label,
        CAST(NULL AS TEXT) AS construction_age_band,
        county,
        CAST(NULL AS INT) AS current_energy_efficiency,
        CAST(NULL AS TEXT) AS current_energy_rating,
        CAST(
            NULLIF("estimated-aircon-kw-rating", '') AS DOUBLE PRECISION
        ) AS estimated_aircon_kw_rating,
        CAST(NULL AS BIGINT) AS energy_consumption_current,
        CAST(NULL AS BIGINT) AS energy_consumption_potential,
        CAST(NULL AS TEXT) AS energy_tariff,
        CAST(NULL AS FLOAT) AS environment_impact_current,
        CAST(NULL AS BIGINT) AS environment_impact_potential,
        CAST(NULL AS FLOAT) AS extension_count,
        CAST("existing-stock-benchmark" AS INT) AS existing_stock_benchmark,
        CAST(NULL AS INT) AS fixed_lighting_outlets_count,
        CAST(NULL AS FLOAT) AS flat_storey_count,
        CAST(NULL AS TEXT) AS flat_top_storey,
        CAST(NULL AS TEXT) AS floor_description,
        CAST(NULL AS TEXT) AS floor_energy_eff,
        CAST(NULL AS TEXT) AS floor_env_eff,
        CAST(NULL AS FLOAT) AS floor_height,
        CAST(NULL AS TEXT) AS floor_level,
        CAST(NULLIF("floor-area", '') AS DOUBLE PRECISION) AS floor_area,
        CAST(NULL AS TEXT) AS glazed_area,
        CAST(NULL AS TEXT) AS glazed_type,
        CAST(NULL AS TEXT) AS heat_loss_corridor,
        CAST(NULL AS FLOAT) AS heating_cost_current,
        CAST(NULL AS FLOAT) AS heating_cost_potential,
        CAST(NULL AS FLOAT) AS hot_water_cost_current,
        CAST(NULL AS FLOAT) AS hot_water_cost_potential,
        CAST(NULL AS TEXT) AS hot_water_energy_eff,
        CAST(NULL AS TEXT) AS hot_water_env_eff,
        CAST(NULL AS TEXT) AS hotwater_description,
        TO_DATE("inspection-date", 'YYYY_MM_DD') AS inspection_date,
        CAST(NULL AS FLOAT) AS lighting_cost_current,
        CAST(NULL AS FLOAT) AS lighting_cost_potential,
        CAST(NULL AS TEXT) AS lighting_description,
        CAST(NULL AS TEXT) AS lighting_energy_eff,
        CAST(NULL AS TEXT) AS lighting_env_eff,
        "lmk-key" AS lmk_key,
        "local-authority" AS local_authority,
        "local-authority-label" AS local_authority_label,
        TO_DATE("lodgement-date", 'YYYY_MM_DD') AS lodgement_date,
        "lodgement-datetime" AS lodgement_datetime,
        CAST(NULL AS INT) AS low_energy_fixed_light_count,
        CAST(NULL AS INT) AS low_energy_lighting,
        "main-heating-fuel" AS main_fuel,
        CAST(NULL AS TEXT) AS main_heating_controls,
        CAST(NULL AS TEXT) AS mainheat_description,
        CAST(NULL AS TEXT) AS mainheat_energy_eff,
        CAST(NULL AS TEXT) AS mainheat_env_eff,
        CAST(NULL AS TEXT) AS mainheatc_energy_eff,
        CAST(NULL AS TEXT) AS mainheatc_env_eff,
        CAST(NULL AS TEXT) AS mainheatcont_description,
        CAST(NULL AS TEXT) AS mains_gas_flag,
        CAST(NULL AS TEXT) AS mechanical_ventilation,
        CAST(NULL AS TEXT) AS multi_glaze_proportion,
        CAST("new-build-benchmark" AS INT) AS new_build_benchmark,
        CAST(NULL AS INT) AS number_habitable_rooms,
        CAST(NULL AS INT) AS number_heated_rooms,
        CAST(NULL AS INT) AS number_open_fireplaces,
        "other-fuel-desc" AS other_fuel_desc,
        CAST(NULLIF("primary-energy-value", '') AS INT) AS primary_energy_value,
        CAST(NULL AS TEXT) AS photo_supply,
        postcode,
        posttown,
        CAST(NULL AS TEXT) AS potential_energy_efficiency,
        CAST(NULL AS TEXT) AS potential_energy_rating,
        "property-type" AS property_type,
        "renewable-sources" AS renewable_sources,
        CAST(NULL AS TEXT) AS roof_description,
        CAST(NULL AS TEXT) AS roof_energy_eff,
        CAST(NULL AS TEXT) AS roof_env_eff,
        CAST(NULL AS TEXT) AS secondheat_description,
        CAST(NULL AS TEXT) AS sheating_energy_eff,
        CAST(NULL AS TEXT) AS sheating_env_eff,
        CAST(NULL AS TEXT) AS solar_water_heating_flag,
        "special-energy-uses" AS special_energy_uses,
        CAST(NULLIF("standard-emissions", '') AS DOUBLE PRECISION) AS standard_emissions,
        CAST(NULLIF("target-emissions", '') AS DOUBLE PRECISION) AS target_emissions,
        CAST(NULL AS TEXT) AS tenure,
        CAST(NULL AS TEXT) AS total_floor_area,
        "transaction-type" AS transaction_type,
        CAST(NULLIF("typical-emissions", '') AS DOUBLE PRECISION) AS typical_emissions,
        CAST(NULL AS FLOAT) AS unheated_corridor_length,
        CAST(NULLIF(uprn, '') AS BIGINT) AS uprn,
        "uprn-source" AS uprn_source,
        CAST(NULL AS TEXT) AS walls_description,
        CAST(NULL AS TEXT) AS walls_energy_eff,
        CAST(NULL AS TEXT) AS walls_env_eff,
        CAST(NULL AS INT) AS wind_turbine_count,
        CAST(NULL AS TEXT) AS windows_description,
        CAST(NULL AS TEXT) AS windows_energy_eff,
        CAST(NULL AS TEXT) AS windows_env_eff
    FROM {{ source('postgres', 'england_nondomestic_certificates') }}

)

UNION

(
    SELECT
        address,
        address1,
        address2,
        address3,
        CAST(NULL AS TEXT) AS asset_rating,
        CAST(NULL AS TEXT) AS asset_rating_band,
        CAST(NULL AS TEXT) AS aircon_present,
        CAST(NULL AS INT) AS ac_inspection_commissioned,
        CAST(NULL AS TEXT) AS aircon_kw_rating,
        CAST("building-reference-number" AS BIGINT) AS building_reference_number,
        CAST(NULL AS TEXT) AS building_level,
        CAST(NULL AS FLOAT) AS building_emissions,
        CAST(NULL AS TEXT) AS building_environment,
        "built-form",
        CAST("co2-emiss-curr-per-floor-area" AS FLOAT) AS co2_emiss_curr_per_floor_area,
        CAST("co2-emissions-current" AS FLOAT) AS co2_emissions_current,
        CAST("co2-emissions-potential" AS FLOAT) AS co2_emissions_potential,
        constituency,
        "constituency-label" AS constituency_label,
        "construction-age-band" AS construction_age_band,
        county,
        CAST("current-energy-efficiency" AS INT) AS current_energy_efficiency,
        "current-energy-rating" AS current_energy_rating,
        CAST(NULL AS FLOAT) AS estimated_aircon_kw_rating,
        CAST(
            NULLIF("energy-consumption-current", '') AS DOUBLE PRECISION
        ) AS energy_consumption_current,
        CAST(
            NULLIF("energy-consumption-potential", '') AS DOUBLE PRECISION
        ) AS energy_consumption_potential,
        "energy-tariff" AS energy_tariff,
        CAST("environment-impact-current" AS FLOAT) AS environment_impact_current,
        CAST("environment-impact-potential" AS BIGINT) AS environment_impact_potential,
        CAST(NULLIF("extension-count", '') AS FLOAT) AS extension_count,
        CAST(NULL AS INT) AS existing_stock_benchmark,
        CAST(NULLIF("fixed-lighting-outlets-count", '') AS INT) AS fixed_lighting_outlets_count,
        CAST(NULLIF("flat-storey-count", '') AS FLOAT) AS flat_storey_count,
        "flat-top-storey" AS flat_top_storey,
        "floor-description" AS floor_description,
        "floor-energy-eff" AS floor_energy_eff,
        "floor-env-eff" AS floor_env_eff,
        CAST(NULLIF("floor-height", '') AS DOUBLE PRECISION) AS floor_height,
        "floor-level" AS floor_level,
        CAST(NULL AS FLOAT) AS floor_area,
        "glazed-area" AS glazed_area,
        "glazed-type" AS glazed_type,
        "heat-loss-corridor" AS heat_loss_corridor,
        CAST(NULLIF("heating-cost-current", '') AS FLOAT) AS heating_cost_current,
        CAST(NULLIF("heating-cost-potential", '') AS FLOAT) AS heating_cost_potential,
        CAST(NULLIF("hot-water-cost-current", '') AS FLOAT) AS hot_water_cost_current,
        CAST(NULLIF("hot-water-cost-potential", '') AS FLOAT) AS hot_water_cost_potential,
        CAST(NULLIF("hot-water-energy-eff", '') AS TEXT) AS hot_water_energy_eff,
        CAST(NULLIF("hot-water-env-eff", '') AS TEXT) AS hot_water_env_eff,
        CAST(NULLIF("hotwater-description", '') AS TEXT) AS hotwater_description,
        TO_DATE("inspection-date", 'YYYY-MM-DD') AS inspection_date,
        CAST(NULLIF("lighting-cost-current", '') AS FLOAT) AS lighting_cost_current,
        CAST(NULLIF("lighting-cost-potential", '') AS FLOAT) AS lighting_cost_potential,
        "lighting-description" AS lighting_description,
        "lighting-energy-eff" AS lighting_energy_eff,
        "lighting-env-eff" AS lighting_env_eff,
        "lmk-key" AS lmk_key,
        "local-authority" AS local_authority,
        "local-authority-label" AS local_authority_label,
        TO_DATE("lodgement-date", 'YYYY-MM-DD') AS lodgement_date,
        "lodgement-datetime" AS lodgement_datetime,
        CAST(NULLIF("low-energy-fixed-light-count", '') AS FLOAT) AS low_energy_fixed_light_count,
        CAST(NULLIF("low-energy-lighting", '') AS FLOAT) AS low_energy_lighting,
        "main-fuel" AS main_fuel,
        "main-heating-controls" AS main_heating_controls,
        "mainheat-description" AS mainheat_description,
        "mainheat-energy-eff" AS mainheat_energy_eff,
        "mainheat-env-eff" AS mainheat_env_eff,
        "mainheatc-energy-eff" AS mainheatc_energy_eff,
        "mainheatc-env-eff" AS mainheatc_env_eff,
        "mainheatcont-description" AS mainheatcont_description,
        "mains-gas-flag" AS mains_gas_flag,
        "mechanical-ventilation" AS mechanical_ventilation,
        "multi-glaze-proportion" AS multi_glaze_proportion,
        CAST(NULL AS INT) AS new_build_benchmark,
        CAST(NULLIF("number-habitable-rooms", '') AS INT) AS number_habitable_rooms,
        CAST(NULLIF("number-heated-rooms", '') AS INT) AS number_heated_rooms,
        CAST(NULLIF("number-open-fireplaces", '') AS INT) AS number_open_fireplaces,
        CAST(NULL AS TEXT) AS other_fuel_desc,
        CAST(NULL AS INT) AS primary_energy_value,
        "photo-supply" AS photo_supply,
        postcode,
        posttown,
        "potential-energy-efficiency" AS potential_energy_efficiency,
        "potential-energy-rating" AS potential_energy_rating,
        "property-type" AS property_type,
        CAST(NULL AS TEXT) AS renewable_sources,
        "roof-description" AS roof_description,
        "roof-energy-eff" AS roof_energy_eff,
        "roof-env-eff" AS roof_env_eff,
        "secondheat-description" AS secondheat_description,
        "sheating-energy-eff" AS sheating_energy_eff,
        "sheating-env-eff" AS sheating_env_eff,
        "solar-water-heating-flag" AS solar_water_heating_flag,
        CAST(NULL AS TEXT) AS special_energy_uses,
        CAST(NULL AS FLOAT) AS standard_emissions,
        CAST(NULL AS FLOAT) AS target_emissions,
        tenure,
        CAST("total-floor-area" AS TEXT) AS total_floor_area,
        "transaction-type" AS transaction_type,
        CAST(NULL AS FLOAT) AS typical_emissions,
        CAST(NULLIF("unheated-corridor-length", '') AS FLOAT) AS unheated_corridor_length,
        CAST(NULLIF(uprn, '') AS BIGINT) AS uprn,
        "uprn-source" AS uprn_source,
        "walls-description" AS walls_description,
        "walls-energy-eff" AS walls_energy_eff,
        "walls-env-eff" AS walls_env_eff,
        CAST(NULLIF("wind-turbine-count", '') AS INT) AS wind_turbine_count,
        "windows-description" AS windows_description,
        "windows-energy-eff" AS windows_energy_eff,
        "windows-env-eff" AS windows_env_eff

    FROM {{ source('postgres', 'england_domestic_certificates') }}
)
