{{ config(materialized = 'table') }}
SELECT
    CAST("walls-env-eff" AS TEXT) AS walls_env_eff,
    CAST(NULLIF("fixed-lighting-outlets-count", '') AS FLOAT) AS fixed_lighting_outlets_count,
    COALESCE(NULLIF(CAST("glazed-area" AS TEXT), ''), 'NO DATA!') AS glazed_area,
    CAST(NULLIF("energy-consumption-potential", '') AS FLOAT) AS energy_consumption_potential,
    CAST(NULLIF("low-energy-fixed-light-count", '') AS FLOAT) AS low_energy_fixed_light_count,
    CAST("secondheat-description" AS TEXT) AS secondheat_description,
    CAST("lmk-key" AS TEXT) AS lmk_key,
    CAST(county AS TEXT) AS county,
    CAST("main-fuel" AS TEXT) AS main_fuel,
    CAST("mains-gas-flag" AS TEXT) AS mains_gas_flag,
    CAST(NULLIF("number-open-fireplaces", '') AS INT) AS number_open_fireplaces,
    CAST("co2-emissions-potential" AS FLOAT) AS co2_emissions_potential,
    CAST(NULLIF("current-energy-efficiency", '') AS FLOAT) AS current_energy_efficiency,
    CAST("walls-energy-eff" AS TEXT) AS walls_energy_eff,
    CAST(NULLIF("number-heated-rooms", '') AS INT) AS number_heated_rooms,
    CAST("floor-env-eff" AS TEXT) AS floor_env_eff,
    CAST("mechanical-ventilation" AS TEXT) AS mechanical_ventilation,
    CAST(NULLIF("photo-supply", '') AS FLOAT) AS photo_supply,
    CAST("mainheat-env-eff" AS TEXT) AS mainheat_env_eff,
    CAST(NULLIF("environment-impact-potential", '') AS FLOAT) AS environment_impact_potential,
    CAST("windows-energy-eff" AS TEXT) AS windows_energy_eff,
    CAST("roof-env-eff" AS TEXT) AS roof_env_eff,
    CAST("total-floor-area" AS FLOAT) AS total_floor_area,
    CAST("flat-top-storey" AS TEXT) AS flat_top_storey,
    CAST(NULLIF("multi-glaze-proportion", '') AS FLOAT) AS multi_glaze_proportion,
    CAST(tenure AS TEXT) AS tenure,
    CAST(posttown AS TEXT) AS posttown,
    CAST(uprn AS TEXT) AS uprn,
    CAST("mainheat-energy-eff" AS TEXT) AS mainheat_energy_eff,
    CAST("current-energy-rating" AS TEXT) AS current_energy_rating,
    CAST(postcode AS TEXT) AS postcode,
    CAST("mainheat-description" AS TEXT) AS mainheat_description,
    CAST("sheating-env-eff" AS TEXT) AS sheating_env_eff,
    CAST("walls-description" AS TEXT) AS walls_description,
    CAST(NULLIF("flat-storey-count", '') AS FLOAT) AS flat_storey_count,
    CAST("potential-energy-rating" AS TEXT) AS potential_energy_rating,
    CAST("hotwater-description" AS TEXT) AS hotwater_description,
    CAST(NULLIF("lighting-cost-current", '') AS FLOAT) AS lighting_cost_current,
    CAST(NULLIF("floor-height", '') AS FLOAT) AS floor_height,
    CAST(NULLIF("lighting-cost-potential", '') AS FLOAT) AS lighting_cost_potential,
    CAST("floor-energy-eff" AS TEXT) AS floor_energy_eff,
    CAST("windows-description" AS TEXT) AS windows_description,
    CAST("sheating-energy-eff" AS TEXT) AS sheating_energy_eff,
    CAST("energy-consumption-current" AS FLOAT) AS energy_consumption_current,
    CAST("potential-energy-efficiency" AS FLOAT) AS potential_energy_efficiency,
    CAST(NULLIF("heating-cost-current", '') AS FLOAT) AS heating_cost_current,
    CAST(NULLIF("hot-water-cost-current", '') AS FLOAT) AS hot_water_cost_current,
    CAST("construction-age-band" AS TEXT) AS construction_age_band,
    CAST("main-heating-controls" AS TEXT) AS main_heating_controls,
    CAST("solar-water-heating-flag" AS TEXT) AS solar_water_heating_flag,
    CAST("built-form" AS TEXT) AS built_form,
    CAST("property-type" AS TEXT) AS property_type,
    CAST(NULLIF("co2-emiss-curr-per-floor-area", '') AS FLOAT) AS co2_emiss_curr_per_floor_area,
    CAST("roof-energy-eff" AS TEXT) AS roof_energy_eff,
    CAST("lighting-env-eff" AS TEXT) AS lighting_env_eff,
    CAST(NULLIF("extension-count", '') AS FLOAT) AS extension_count,
    CAST("floor-level" AS TEXT) AS floor_level,
    CAST("lodgement-datetime" AS TEXT) AS lodgement_datetime,
    CAST("heat-loss-corridor" AS TEXT) AS heat_loss_corridor,
    CAST("mainheatc-env-eff" AS TEXT) AS mainheatc_env_eff,
    CAST("lighting-description" AS TEXT) AS lighting_description,
    CAST("windows-env-eff" AS TEXT) AS windows_env_eff,
    CAST("hot-water-energy-eff" AS TEXT) AS hot_water_energy_eff,
    CAST("transaction-type" AS TEXT) AS transaction_type,
    CAST("mainheatc-energy-eff" AS TEXT) AS mainheatc_energy_eff,
    CAST(NULLIF("co2-emissions-current", '') AS FLOAT) AS co2_emissions_current,
    CAST("local-authority-label" AS TEXT) AS local_authority_label,
    CAST(address AS TEXT) AS address,
    CAST(address1 AS TEXT) AS address1,
    CAST(address2 AS TEXT) AS address2,
    CAST(address3 AS TEXT) AS address3,
    CAST("roof-description" AS TEXT) AS roof_description,
    CAST("hot-water-env-eff" AS TEXT) AS hot_water_env_eff,
    CAST(NULLIF("environment-impact-current", '') AS FLOAT) AS environment_impact_current,
    CAST("energy-tariff" AS TEXT) AS energy_tariff,
    CAST(NULLIF("hot-water-cost-potential", '') AS FLOAT) AS hot_water_cost_potential,
    CAST("glazed-type" AS TEXT) AS glazed_type,
    CAST("lighting-energy-eff" AS TEXT) AS lighting_energy_eff,
    CAST(NULLIF("heating-cost-potential", '') AS FLOAT) AS heating_cost_potential,
    CAST("local-authority" AS TEXT) AS local_authority,
    CAST("constituency-label" AS TEXT) AS constituency_label,
    CAST("mainheatcont-description" AS TEXT) AS mainheatcont_description,
    CAST("building-reference-number" AS TEXT) AS building_reference_number,
    CAST(NULLIF("low-energy-lighting", '') AS INT) AS low_energy_lighting,
    CAST(NULLIF("unheated-corridor-length", '') AS FLOAT) AS unheated_corridor_length,
    CAST(constituency AS TEXT) AS constituency,
    CAST("floor-description" AS TEXT) AS floor_description,
    CAST(NULLIF("wind-turbine-count", '') AS INT) AS wind_turbine_count,
    CAST("inspection-date" AS DATE) AS inspection_date,
    CAST("uprn-source" AS TEXT) AS uprn_source,
    CAST("lodgement-date" AS DATE) AS lodgement_date,
    CAST(NULLIF("number-habitable-rooms", '') AS INT) AS number_habitable_rooms,
    _airbyte_ab_id,
    _airbyte_emitted_at,
    _airbyte_normalized_at,
    _airbyte_domestic_ce__ficates_search_hashid AS _airbyte_hashid,
    'domestic' AS certificate_type
FROM
    {{ source('postgres', 'domestic_certificates_search') }}

UNION

SELECT
    CAST(NULL AS TEXT) AS walls_env_eff,
    CAST(NULL AS FLOAT) AS fixed_lighting_outlets_count,
    CAST('NO DATA!' AS TEXT) AS glazed_area,
    CAST(NULL AS FLOAT) AS energy_consumption_potential,
    CAST(NULL AS FLOAT) AS low_energy_fixed_light_count,
    CAST(NULL AS TEXT) AS secondheat_description,
    CAST("lmk-key" AS TEXT) AS lmk_key,
    CAST(county AS TEXT) AS county,
    CAST(NULL AS TEXT) AS main_fuel,
    CAST(NULL AS TEXT) AS mains_gas_flag,
    CAST(NULL AS INT) AS number_open_fireplaces,
    CAST(NULL AS FLOAT) AS co2_emissions_potential,
    CAST(NULL AS FLOAT) AS current_energy_efficiency,
    CAST(NULL AS TEXT) AS walls_energy_eff,
    CAST(NULL AS INT) AS number_heated_rooms,
    CAST(NULL AS TEXT) AS floor_env_eff,
    CAST(NULL AS TEXT) AS mechanical_ventilation,
    CAST(NULL AS FLOAT) AS photo_supply,
    CAST(NULL AS TEXT) AS mainheat_env_eff,
    CAST(NULL AS FLOAT) AS environment_impact_potential,
    CAST(NULL AS TEXT) AS windows_energy_eff,
    CAST(NULL AS TEXT) AS roof_env_eff,
    CAST(NULL AS FLOAT) AS total_floor_area,
    CAST(NULL AS TEXT) AS flat_top_storey,
    CAST(NULL AS FLOAT) AS multi_glaze_proportion,
    CAST(NULL AS TEXT) AS tenure,
    CAST(posttown AS TEXT) AS posttown,
    CAST(uprn AS TEXT) AS uprn,
    CAST(NULL AS TEXT) AS mainheat_energy_eff,
    CAST(NULL AS TEXT) AS current_energy_rating,
    CAST(postcode AS TEXT) AS postcode,
    CAST(NULL AS TEXT) AS mainheat_description,
    CAST(NULL AS TEXT) AS sheating_env_eff,
    CAST(NULL AS TEXT) AS walls_description,
    CAST(NULL AS FLOAT) AS flat_storey_count,
    CAST(NULL AS TEXT) AS potential_energy_rating,
    CAST(NULL AS TEXT) AS hotwater_description,
    CAST(NULL AS FLOAT) AS lighting_cost_current,
    CAST(NULL AS FLOAT) AS floor_height,
    CAST(NULL AS FLOAT) AS lighting_cost_potential,
    CAST(NULL AS TEXT) AS floor_energy_eff,
    CAST(NULL AS TEXT) AS windows_description,
    CAST(NULL AS TEXT) AS sheating_energy_eff,
    CAST(NULL AS FLOAT) AS energy_consumption_current,
    CAST(NULL AS FLOAT) AS potential_energy_efficiency,
    CAST(NULL AS FLOAT) AS heating_cost_current,
    CAST(NULL AS FLOAT) AS hot_water_cost_current,
    CAST(NULL AS TEXT) AS construction_age_band,
    CAST(NULL AS TEXT) AS main_heating_controls,
    CAST(NULL AS TEXT) AS solar_water_heating_flag,
    CAST(NULL AS TEXT) AS built_form,
    CAST("property-type" AS TEXT) AS property_type,
    CAST(NULL AS FLOAT) AS co2_emiss_curr_per_floor_area,
    CAST(NULL AS TEXT) AS roof_energy_eff,
    CAST(NULL AS TEXT) AS lighting_env_eff,
    CAST(NULL AS FLOAT) AS extension_count,
    CAST(NULL AS TEXT) AS floor_level,
    CAST("lodgement-datetime" AS TEXT) AS lodgement_datetime,
    CAST(NULL AS TEXT) AS heat_loss_corridor,
    CAST(NULL AS TEXT) AS mainheatc_env_eff,
    CAST(NULL AS TEXT) AS lighting_description,
    CAST(NULL AS TEXT) AS windows_env_eff,
    CAST(NULL AS TEXT) AS hot_water_energy_eff,
    CAST("transaction-type" AS TEXT) AS transaction_type,
    CAST(NULL AS TEXT) AS mainheatc_energy_eff,
    CAST(NULL AS FLOAT) AS co2_emissions_current,
    CAST("local-authority-label" AS TEXT) AS local_authority_label,
    CAST(address AS TEXT) AS address,
    CAST(address1 AS TEXT) AS address1,
    CAST(address2 AS TEXT) AS address2,
    CAST(address3 AS TEXT) AS address3,
    CAST(NULL AS TEXT) AS roof_description,
    CAST(NULL AS TEXT) AS hot_water_env_eff,
    CAST(NULL AS FLOAT) AS environment_impact_current,
    CAST(NULL AS TEXT) AS energy_tariff,
    CAST(NULL AS FLOAT) AS hot_water_cost_potential,
    CAST(NULL AS TEXT) AS glazed_type,
    CAST(NULL AS TEXT) AS lighting_energy_eff,
    CAST(NULL AS FLOAT) AS heating_cost_potential,
    CAST("local-authority" AS TEXT) AS local_authority,
    CAST("constituency-label" AS TEXT) AS constituency_label,
    CAST(NULL AS TEXT) AS mainheatcont_description,
    CAST("building-reference-number" AS TEXT) AS building_reference_number,
    CAST(NULL AS INT) AS low_energy_lighting,
    CAST(NULL AS FLOAT) AS unheated_corridor_length,
    CAST(constituency AS TEXT) AS constituency,
    CAST(NULL AS TEXT) AS floor_description,
    CAST(NULL AS INT) AS wind_turbine_count,
    CAST("inspection-date" AS DATE) AS inspection_date,
    CAST("uprn-source" AS TEXT) AS uprn_source,
    CAST("lodgement-date" AS DATE) AS lodgement_date,
    CAST(NULL AS INT) AS number_habitable_rooms,
    _airbyte_ab_id,
    _airbyte_emitted_at,
    _airbyte_normalized_at,
    _airbyte_non_domesti__ficates_search_hashid AS _airbyte_hashid,
    'non_domestic' AS certificate_type
FROM
    {{ source('postgres', 'non_domestic_certificates_search') }}
