{{ config(materialized = 'table')}}
(
    SELECT
        CAST(NULL AS BIGINT) AS uprn,
        CAST(NULL AS TEXT) AS uprn_source,
        CAST(NULL AS TEXT) AS lmk_key,
        CAST(NULL AS TEXT) AS county,
        CAST(NULL AS FLOAT) AS flat_storey_count,
        CAST(NULL AS TEXT) AS lodgement_datetime,
        building_reference_number,
        osg_reference_number,
        address1,
        address2,
        posttown,
        CAST("postcode" AS TEXT) AS postcode,
        CONCAT(address1, ',', address2) AS address,
        inspection_date,
        lodgement_date,
        property_type,
        total_floor_area,
        current_energy_performance_rating,
        current_energy_performance_band,
        current_energy_efficiency,
        potential_energy_performance_rating,
        potential_energy_performance_band,
        potential_energy_efficiency,
        new_build_energy_performance_rating,
        new_build_energy_performance_band,
        environment_impact_current,
        environment_impact_potential,
        co2_emiss_curr_per_floor_area,
        current_environmental_performance_band,
        potential_environmental_performance_band,
        meets_2002_standard,
        asset_rating,
        asset_rating_band,
        building_emissions,
        renewable_sources,
        electricity_source,
        building_environment,
        primary_energy_value,
        approximate_energy_use,
        local_authority,
        data_zone,
        constituency,
        constituency_label,
        transaction_type,
        target_emissions,
        data_zone_2011,
        created_at,
        wall_description,
        wall_energy_eff,
        walL_env_eff,
        roof_description,
        roof_energy_eff,
        roof_env_eff,
        floor_description,
        floor_energy_eff,
        floor_env_eff,
        windows_description,
        windows_energy_eff,
        windows_env_eff,
        mainheat_description,
        mainheat_energy_eff,
        mainheat_env_eff,
        mainheatcont_description,
        mainheatc_energy_eff,
        mainheatc_env_eff,
        secondheat_description,
        sheating_energy_eff,
        sheating_env_eff,
        hotwater_description,
        hot_water_energy_eff,
        hot_water_env_eff,
        lighting_description,
        lighting_energy_eff,
        lighting_env_eff,
        air_tightness_description,
        air_tightness_energy_eff,
        air_tightness_env_eff,
        CAST("co2_emissions_current" AS TEXT) AS co2_emissions_current,
        CAST("co2_emissions_potential" AS TEXT) AS co2_emissions_potential,
        heating_cost_current,
        heating_cost_potential,
        hot_water_cost_current,
        hot_water_cost_potential,
        lighting_cost_current,
        lighting_cost_potential,
        energy_consumption_current,
        energy_consumption_potential,
        space_heating_demand,
        lzc_energy_sources,
        water_heating_demand,
        impact_loft_insulation,
        impact_cavity_wall_insulation,
        impact_solid_wall_insulation,
        construction_age_band,
        floor_height,
        extension_count,
        fixed_lighting_outlets_count,
        low_energy_fixed_light_count,
        low_energy_lighting,
        floor_level,
        flat_top_storey,
        glazed_area,
        number_habitable_rooms,
        heat_loss_corridor,
        number_heated_rooms,
        local_authority_label,
        mains_gas_flag,
        main_heating_category,
        main_heating_controls,
        main_fuel,
        mechanical_ventilation,
        energy_tariff,
        multi_glaze_proportion,
        glazed_type,
        number_open_fireplaces,
        photo_supply,
        solar_water_heating_flag,
        tenure,
        unheated_corridor_length,
        built_form,
        wind_turbine_count,
        three_year_energy_cost_current,
        three_year_energy_savings_potential,
        type_of_assessment,
        CAST(NULL AS FLOAT) AS standard_emissions,
        CAST(NULL AS FLOAT) AS typical_emissions,
        CAST(NULL AS TEXT) AS special_energy_uses,
        CAST(NULL AS TEXT) AS other_fuel_desc,
        CAST(NULL AS INT) AS new_build_benchmark,
        CAST(NULL AS INT) AS existing_stock_benchmark,
        CAST(NULL AS FLOAT) AS estimated_aircon_kw_rating,
        CAST(NULL AS FLOAT) AS ac_inspection_commissioned,
        CAST(NULL AS TEXT) AS building_level,
        certificate_type
    FROM {{ ref('stg_scottish_epc_certificates') }}
    -- ORDER BY "postcode" ASC
)

UNION

(
    SELECT
        CAST(NULL AS BIGINT) AS uprn,
        CAST(NULL AS TEXT) AS uprn_source,
        CAST(NULL AS TEXT) AS lmk_key,
        CAST(NULL AS TEXT) AS county,
        CAST(NULL AS FLOAT) AS flat_storey_count,
        CAST(NULL AS TEXT) AS lodgement_datetime,
        CAST("BUILDING_REFERENCE_NUMBER" AS BIGINT) AS building_reference_number,
        "OSG_REFERENCE_NUMBER" AS osg_reference_number,
        CAST("ADDRESS1" AS TEXT) AS address1,
        CAST("ADDRESS2" AS TEXT) AS address2,
        CAST("ADDRESS3" AS TEXT) AS posttown,
        CAST("POSTCODE" AS TEXT) AS postcode,
        CONCAT("ADDRESS1", "ADDRESS3", "POSTCODE") AS address,
        TO_DATE("INSPECTION_DATE", 'dd Month YYYY') AS inspection_date,
        TO_DATE("LODGEMENT_DATE", 'YYYY-MM-DD') AS lodgement_date,
        "PROPERTY_TYPE" AS property_type,
        CAST("TOTAL_FLOOR_AREA" AS TEXT) AS total_floor_area,
        CAST(NULL AS TEXT) AS current_energy_performance_rating,
        CAST("CURRENT_ENERGY_RATING" AS TEXT) AS current_energy_performance_band,
        CAST("CURRENT_ENERGY_EFFICIENCY" AS INT) AS current_energy_efficiency,
        CAST(NULL AS TEXT) AS potential_energy_performance_rating,
        "POTENTIAL_ENERGY_RATING" AS potential_energy_performance_band,
        "POTENTIAL_ENERGY_EFFICIENCY" AS potential_energy_efficiency,
        CAST(NULL AS INT) AS new_build_energy_performance_rating,
        CAST(NULL AS TEXT) AS new_build_energy_performance_band,
        CAST("ENVIRONMENT_IMPACT_CURRENT" AS FLOAT) AS environment_impact_current,
        CAST("ENVIRONMENT_IMPACT_POTENTIAL" AS FLOAT) AS environment_impact_potential,
        CAST("CO2_EMISS_CURR_PER_FLOOR_AREA" AS FLOAT) AS co2_emiss_curr_per_floor_area,
        "CURRENT_ENVIRONMENTAL_RATING" AS current_environmental_performance_band,
        "POTENTIAL_ENVIRONMENTAL_RATING" AS potential_environmental_performance_band,
        CAST(NULL AS TEXT) AS meets_2002_standard,
        CAST(NULL AS TEXT) AS asset_rating,
        CAST(NULL AS TEXT) AS asset_rating_band,
        CAST(NULL AS FLOAT) AS building_emissions,
        CAST(NULL AS TEXT) AS renewable_sources,
        CAST(NULL AS TEXT) AS electricity_source,
        CAST(NULL AS TEXT) AS building_environment,
        CAST(NULL AS INT) AS primary_energy_value,
        CAST(NULL AS INT) AS approximate_energy_use,
        CAST(NULL AS TEXT) AS local_authority,
        "DATA_ZONE" AS data_zone,
        "CONSTITUENCY" AS constituency,
        "CONSTITUENCY_LABEL" AS constituency_label,
        "TRANSACTION_TYPE" AS transaction_type,
        CAST(NULL AS FLOAT) AS target_emissions,
        "DATA_ZONE_2011" AS data_zone_2011,
        "CREATED_AT" AS created_at,
        "WALL_DESCRIPTION" AS wall_description,
        "WALL_ENERGY_EFF" AS wall_energy_eff,
        "WALL_ENV_EFF" AS wall_env_eff,
        "ROOF_DESCRIPTION" AS roof_description,
        "ROOF_ENERGY_EFF" AS roof_energy_eff,
        "ROOF_ENV_EFF" AS roof_env_eff,
        "FLOOR_DESCRIPTION" AS floor_description,
        "FLOOR_ENERGY_EFF" AS floor_energy_eff,
        "FLOOR_ENV_EFF" AS floor_env_eff,
        "WINDOWS_DESCRIPTION" AS windows_description,
        "WINDOWS_ENERGY_EFF" AS windows_energy_eff,
        "WINDOWS_ENV_EFF" AS windows_env_eff,
        "MAINHEAT_DESCRIPTION" AS mainheat_description,
        "MAINHEAT_ENERGY_EFF" AS mainheat_energy_eff,
        "MAINHEAT_ENV_EFF" AS mainheat_env_eff,
        "MAINHEATCONT_DESCRIPTION" AS mainheatcont_description,
        "MAINHEATC_ENERGY_EFF" AS mainheatc_energy_eff,
        "MAINHEATC_ENV_EFF" AS mainheatc_env_eff,
        "SECONDHEAT_DESCRIPTION" AS secondheat_description,
        "SHEATING_ENERGY_EFF" AS sheating_energy_eff,
        "SHEATING_ENV_EFF" AS sheating_env_eff,
        "HOTWATER_DESCRIPTION" AS hotwater_description,
        "HOT_WATER_ENERGY_EFF" AS hot_water_energy_eff,
        "HOT_WATER_ENV_EFF" AS hot_water_env_eff,
        "LIGHTING_DESCRIPTION" AS lighting_description,
        "LIGHTING_ENERGY_EFF" AS lighting_energy_eff,
        "LIGHTING_ENV_EFF" AS lighting_env_eff,
        "AIR_TIGHTNESS_DESCRIPTION" AS air_tightness_description,
        "AIR_TIGHTNESS_ENERGY_EFF" AS air_tightness_energy_eff,
        "AIR_TIGHTNESS_ENV_EFF" AS air_tightness_env_eff,
        CAST("CO2_EMISSIONS_CURRENT" AS TEXT) AS co2_emissions_current,
        CAST("CO2_EMISSIONS_POTENTIAL" AS TEXT) AS co2_emissions_potential,
        CAST("HEATING_COST_CURRENT" AS FLOAT) AS heating_cost_current,
        CAST("HEATING_COST_POTENTIAL" AS FLOAT) AS heating_cost_potential,
        CAST("HOT_WATER_COST_CURRENT" AS FLOAT) AS hot_water_cost_current,
        CAST("HOT_WATER_COST_POTENTIAL" AS FLOAT) AS hot_water_cost_potential,
        CAST("LIGHTING_COST_CURRENT" AS FLOAT) AS lighting_cost_current,
        CAST("LIGHTING_COST_POTENTIAL" AS FLOAT) AS lighting_cost_potential,
        CAST("ENERGY_CONSUMPTION_POTENTIAL" AS FLOAT) AS energy_consumption_potential,
        CAST("ENERGY_CONSUMPTION_CURRENT" AS FLOAT) AS energy_consumption_current,
        "SPACE_HEATING_DEMAND" AS space_heating_demand,
        CAST("LZC_ENERGY_SOURCES" AS TEXT) AS lzc_energy_sources,
        "WATER_HEATING_DEMAND" AS water_heating_demand,
        "IMPACT_LOFT_INSULATION" AS impact_loft_insulation,
        "IMPACT_CAVITY_WALL_INSULATION" AS impact_cavity_wall_insulation,
        "IMPACT_SOLID_WALL_INSULATION" AS impact_solid_wall_insulation,
        "CONSTRUCTION_AGE_BAND" AS construction_age_band,
        CAST("FLOOR_HEIGHT" AS FLOAT) AS floor_height,
        CAST("EXTENSION_COUNT" AS INT) AS extension_count,
        CAST("FIXED_LIGHTING_OUTLETS_COUNT" AS FLOAT) AS fixed_lighting_outlets_count,
        CAST("LOW_ENERGY_FIXED_LIGHT_COUNT" AS FLOAT) AS low_energy_fixed_light_count,
        CAST("LOW_ENERGY_LIGHTING" AS FLOAT) AS low_energy_lighting,
        "FLOOR_LEVEL" AS floor_level,
        "FLAT_TOP_STOREY" AS flat_top_storey,
        "GLAZED_AREA" AS glazed_area,
        CAST("NUMBER_HABITABLE_ROOMS" AS INT) AS number_habitable_rooms,
        "HEAT_LOSS_CORRIDOOR" AS heat_loss_corridor,
        CAST("NUMBER_HEATED_ROOMS" AS INT) AS number_heated_rooms,
        "LOCAL_AUTHORITY_LABEL" AS local_authority_label,
        "MAINS_GAS_FLAG" AS mains_gas_flag,
        "MAIN_HEATING_CATEGORY" AS main_heating_category,
        "MAIN_HEATING_CONTROLS" AS main_heating_controls,
        "MAIN_FUEL" AS main_fuel,
        "MECHANICAL_VENTILATION" AS mechanical_ventilation,
        "ENERGY_TARIFF" AS energy_tariff,
        "MULTI_GLAZE_PROPORTION" AS multi_glaze_proportion,
        "GLAZED_TYPE" AS glazed_type,
        CAST("NUMBER_OPEN_FIREPLACES" AS INT) AS number_open_fireplaces,
        "PHOTO_SUPPLY" AS photo_supply,
        "SOLAR_WATER_HEATING_FLAG" AS solar_water_heating_flag,
        "TENURE" AS tenure,
        CAST("UNHEATED_CORRIDOR_LENGTH" AS FLOAT) AS unheated_corridor_length,
        "BUILT_FORM" AS built_form,
        CAST("WIND_TURBINE_COUNT" AS INT) AS wind_turbine_count,
        CAST("3_YR_ENERGY_COST_CURRENT" AS FLOAT) AS three_year_energy_cost_current,
        CAST("3_YR_ENERGY_SAVINGS_POTENTIAL" AS FLOAT) AS three_year_energy_savings_potential,
        "TYPE_OF_ASSESSMENT" AS type_of_assessment,
        CAST(NULL AS FLOAT) AS standard_emissions,
        CAST(NULL AS FLOAT) AS typical_emissions,
        CAST(NULL AS TEXT) AS special_energy_uses,
        CAST(NULL AS TEXT) AS other_fuel_desc,
        CAST(NULL AS INT) AS new_build_benchmark,
        CAST(NULL AS INT) AS existing_stock_benchmark,
        CAST(NULL AS FLOAT) AS estimated_aircon_kw_rating,
        CAST(NULL AS INT) AS ac_inspection_commissioned,
        CAST(NULL AS TEXT) AS building_level,
        CAST(NULL AS TEXT) AS certificate_type
    FROM {{ source('postgres', 'northern_ireland_epc')}}

)

UNION
(
    SELECT
        uprn,
        uprn_source,
        lmk_key,
        county,
        flat_storey_count,
        CAST("lodgement_datetime" AS TEXT) AS lodgement_datetime,
        building_reference_number,
        CAST(NULL AS TEXT) AS osg_reference_number,
        address1,
        address2,
        posttown,
        postcode,
        address,
        inspection_date,
        lodgement_date,
        property_type,
        total_floor_area,
        "current_energy_rating" AS current_energy_performance_band,
        CAST(NULL AS TEXT) AS current_energy_performance_rating,
        current_energy_efficiency,
        CAST(NULL AS TEXT) AS potential_energy_performance_rating,
        "potential_energy_rating" AS potential_energy_performance_band,
        CAST(NULL AS TEXT) AS potential_energy_efficiency,
        CAST(NULL AS INT) AS new_build_energy_performance_rating,
        CAST(NULL AS TEXT) AS new_build_energy_performance_band,
        environment_impact_current,
        environment_impact_potential,
        co2_emiss_curr_per_floor_area,
        CAST(NULL AS TEXT) AS current_environmental_performance_band,
        CAST(NULL AS TEXT) AS potential_environmental_rating,
        CAST(NULL AS TEXT) AS meets_2002_standard,
        CAST(NULL AS TEXT) AS asset_rating,
        CAST(NULL AS TEXT) AS asset_rating_band,
        CAST(NULL AS FLOAT) AS building_emissions,
        CAST(NULL AS TEXT) AS renewable_sources,
        CAST(NULL AS TEXT) AS electricity_source,
        CAST(NULL AS TEXT) AS building_environment,
        CAST(NULL AS INT) AS primary_energy_value,
        CAST(NULL AS INT) AS approximate_energy_use,
        local_authority,
        CAST(NULL AS TEXT) AS data_zone,
        constituency,
        constituency_label,
        CAST(NULL AS TEXT) AS transaction_type,
        CAST(NULL AS FLOAT) AS target_emissions,
        CAST(NULL AS TEXT) AS data_zone_2011,
        CAST(NULL AS TEXT) AS created_at,
        "walls_description" AS wall_description,
        "walls_energy_eff" AS wall_energy_eff,
        "walls_env_eff" AS wall_env_eff,
        roof_description,
        roof_energy_eff,
        roof_env_eff,
        floor_description,
        floor_energy_eff,
        floor_env_eff,
        windows_description,
        windows_energy_eff,
        windows_env_eff,
        mainheat_description,
        mainheat_energy_eff,
        mainheat_env_eff,
        mainheatcont_description,
        mainheatc_energy_eff,
        mainheatc_env_eff,
        secondheat_description,
        sheating_env_eff,
        sheating_energy_eff,
        hotwater_description,
        hot_water_energy_eff,
        hot_water_env_eff,
        lighting_description,
        lighting_energy_eff,
        lighting_env_eff,
        CAST(NULL AS TEXT) AS air_tightness_env_eff,
        CAST(NULL AS TEXT) AS air_tightness_description,
        CAST(NULL AS TEXT) AS air_tightness_energy_eff,
        CAST("co2_emissions_current" AS TEXT) AS co2_emissions_current,
        CAST("co2_emissions_potential" AS TEXT) AS co2_emissions_potential,
        heating_cost_current,
        heating_cost_potential,
        hot_water_cost_current,
        hot_water_cost_potential,
        lighting_cost_current,
        lighting_cost_potential,
        energy_consumption_current,
        energy_consumption_potential,
        CAST(NULL AS TEXT) AS lzc_energy_sources,
        CAST(NULL AS TEXT) AS space_heating_demand,
        CAST(NULL AS TEXT) AS water_heating_demand,
        CAST(NULL AS TEXT) AS impact_loft_insulation,
        CAST(NULL AS TEXT) AS impact_cavity_wall_insulation,
        CAST(NULL AS TEXT) AS impact_solid_wall_insulation,
        construction_age_band,
        floor_height,
        extension_count,
        fixed_lighting_outlets_count,
        low_energy_fixed_light_count,
        low_energy_lighting,
        floor_level,
        flat_top_storey,
        glazed_area,
        number_habitable_rooms,
        heat_loss_corridor,
        number_heated_rooms,
        local_authority_label,
        CAST(NULL AS TEXT) AS mains_gas_flag,
        CAST(NULL AS TEXT) AS main_heating_category,
        main_heating_controls,
        main_fuel,
        mechanical_ventilation,
        energy_tariff,
        multi_glaze_proportion,
        glazed_type,
        number_open_fireplaces,
        photo_supply,
        solar_water_heating_flag,
        tenure,
        unheated_corridor_length,
        built_form,
        wind_turbine_count,
        CAST(NULL AS FLOAT) AS three_year_energy_cost_current,
        CAST(NULL AS FLOAT) AS three_year_energy_savings_potential,
        CAST(NULL AS TEXT) AS type_of_assessment,
        standard_emissions,
        typical_emissions,
        special_energy_uses,
        other_fuel_desc,
        new_build_benchmark,
        existing_stock_benchmark,
        estimated_aircon_kw_rating,
        ac_inspection_commissioned,
        building_level,
        CAST(NULL AS TEXT) AS certificate_type
    FROM {{ ref('stg_england_wales_certificates') }}
    LIMIT 20
)
