{{ config(materialized = 'table') }}

(
    SELECT
        "RPC" AS rpc,
        "POSTCODE" AS postcode,
        "LOGICAL_STATUS_CODE" AS logical_status_code,
        "COUNTRY_CODE_DESCRIPTION",
        CAST("X_COORDINATE" AS FLOAT) AS x_coordinate,
        TO_DATE("LAST_UPDATE_DATE", 'DD/MM/YYYY') AS last_update_date,
        "CLASSIFICATION_CODE_DESCRIPTION" AS classification_code_description,
        "ORGANISATION_NAME" AS organisation_name,
        CAST("UDPRN" AS INT) AS udprn,
        "STATUS" AS status,
        CAST("PARENT_UPRN" AS BIGINT) AS parent_uprn,
        "POSTAL_ADDRESS_CODE" AS postal_address_code,
        "LOCAL_CUSTODIAN_CODE_DESCRIPTION" AS local_custodian_code_description,
        "DELIVERY_POINT_SUFFIX" AS delivery_point_suffix,
        "BUILDING_NUMBER" AS building_number,
        "THOROUGHFARE_NAME" AS thoroughfare_name,
        "LANGUAGE",
        "DEPENDENT_LOCALITY" AS dependent_locality,
        "BLPU_STATE_CODE_DESCRIPTION" AS blpu_state_code_description,
        "BLPU_STATE_CODE" AS blpu_state_code,
        "LOCAL_CUSTODIAN_CODE" AS local_custodian_code,
        TO_DATE("BLPU_STATE_DATE", 'DD/MM/YYYY') AS blpu_state_date,
        "DEPENDENT_THOROUGHFARE_NAME" AS dependent_thoroughfare_name,
        "POST_TOWN" AS post_town,
        "BUILDING_NAME" AS building_name,
        "SUB_BUILDING_NAME" AS sub_building_name,
        "POSTAL_ADDRESS_CODE_DESCRIPTION" AS postal_address_code_description,
        CAST("UPRN" AS BIGINT) AS uprn,
        "TOPOGRAPHY_LAYER_TOID" AS topography_layer_toid,
        "ADDRESS" AS address,
        CAST("Y_COORDINATE" AS FLOAT) AS y_coordinate,
        "MATCH_DESCRIPTION" AS match_description,
        "CLASSIFICATION_CODE" AS classification_code,
        TO_DATE("ENTRY_DATE", 'DD/MM/YYYY') AS entry_date,
        "MATCH" AS match,
        "COUNTRY_CODE" AS country_code,
        _airbyte_raw_id,
        _airbyte_extracted_at,
        'DPA' AS os_source
    FROM {{ source('postgres', 'os_aberdeen_dpa') }}
)

UNION

(
    SELECT
        "RPC" AS rpc,
        "POSTCODE_LOCATOR" AS postcode,
        "LOGICAL_STATUS_CODE" AS logical_status_code,
        "COUNTRY_CODE_DESCRIPTION" AS country_code_description,
        CAST("X_COORDINATE" AS FLOAT) AS x_coordinate,
        TO_DATE("LAST_UPDATE_DATE", 'DD/MM/YYYY') AS last_update_date,
        "CLASSIFICATION_CODE_DESCRIPTION" AS classification_code_description,
        'N/A' AS organisation_name,
        CAST(NULL AS INT) AS udprn,
        "STATUS" AS status,
        CAST("PARENT_UPRN" AS BIGINT) AS parent_uprn,
        "POSTAL_ADDRESS_CODE" AS postal_address_code,
        "LOCAL_CUSTODIAN_CODE_DESCRIPTION" AS local_custodian_code_description,
        'N/A' AS delivery_point_suffix,
        'N/A' AS building_number,
        'N/A' AS thoroughfare_name,
        "LANGUAGE",
        'N/A' AS dependent_locality,
        "BLPU_STATE_CODE_DESCRIPTION" AS blpu_state_code_description,
        "BLPU_STATE_CODE" AS blpu_state_code,
        "LOCAL_CUSTODIAN_CODE" AS local_custodian_code,
        TO_DATE("BLPU_STATE_DATE", 'DD/MM/YYYY') AS blpu_state_date,
        'N/A' AS dependent_thoroughfare_name,
        'N/A' AS post_town,
        'N/A' AS building_name,
        'N/A' AS sub_building_name,
        "POSTAL_ADDRESS_CODE_DESCRIPTION" AS postal_address_code_description,
        CAST("UPRN" AS BIGINT) AS uprn,
        "TOPOGRAPHY_LAYER_TOID" AS topography_layer_toid,
        "ADDRESS" AS address,
        CAST("Y_COORDINATE" AS FLOAT) AS y_coordinate,
        "MATCH_DESCRIPTION" AS match_description,
        "CLASSIFICATION_CODE" AS classification_code,
        TO_DATE("ENTRY_DATE", 'DD/MM/YYYY') AS entry_date,
        "MATCH" AS match,
        "COUNTRY_CODE" AS country_code,
        _airbyte_raw_id,
        _airbyte_extracted_at,
        'LPI' AS os_source
    FROM {{ source('postgres', 'os_aberdeen_lpi') }}
    WHERE "CLASSIFICATION_CODE_DESCRIPTION" NOT IN (
        'Street Record',
        'Property Shell',
        'Static Water',
        'Electricity Sub-Station',
        'Postal Box',
        'Bus Shelter',
        'Additional Mail / Packet Addressee',
        'Hopper / Silo / Cistern / Tank',
        'General Storage Land',
        'Telecommunication',
        'House Boat',
        'Equestrian',
        'Telephone Box',
        'PO Box',
        'Advertising Hoarding',
        'Allocated Parking'
    )
)
