{{ config(materialized = 'table') }}
SELECT
    -- England & Wales Domestic
    CAST("walls-env-eff" AS TEXT) AS walls_env_eff,
    CAST(NULLIF("fixed-lighting-outlets-count", '') AS FLOAT) AS fixed_lighting_outlets_count,
    COALESCE(NULLIF(CAST("glazed-area" AS TEXT), ''), 'NO DATA!') AS glazed_area,
    CAST(NULLIF("energy-consumption-potential", '') AS FLOAT) AS energy_consumption_potential,
    CAST(NULLIF("low-energy-fixed-light-count", '') AS FLOAT) AS low_energy_fixed_light_count,
    CAST("secondheat-description" AS TEXT) AS secondheat_description,
    CAST("lmk-key" AS TEXT) AS lmk_key,
    CAST(county AS TEXT) AS county,
    CAST("main-fuel" AS TEXT) AS main_fuel,
    CAST("mains-gas-flag" AS TEXT) AS mains_gas_flag,
    CAST(NULLIF("number-open-fireplaces", '') AS INT) AS number_open_fireplaces,
    CAST("co2-emissions-potential" AS FLOAT) AS co2_emissions_potential,
    CAST(NULLIF("current-energy-efficiency", '') AS FLOAT) AS current_energy_efficiency,
    CAST("walls-energy-eff" AS TEXT) AS walls_energy_eff,
    CAST(NULLIF("number-heated-rooms", '') AS INT) AS number_heated_rooms,
    CAST("floor-env-eff" AS TEXT) AS floor_env_eff,
    CAST("mechanical-ventilation" AS TEXT) AS mechanical_ventilation,
    CAST(NULLIF("photo-supply", '') AS FLOAT) AS photo_supply,
    CAST("mainheat-env-eff" AS TEXT) AS mainheat_env_eff,
    CAST(NULLIF("environment-impact-potential", '') AS FLOAT) AS environment_impact_potential,
    CAST("windows-energy-eff" AS TEXT) AS windows_energy_eff,
    CAST("roof-env-eff" AS TEXT) AS roof_env_eff,
    CAST("total-floor-area" AS FLOAT) AS total_floor_area,
    CAST("flat-top-storey" AS TEXT) AS flat_top_storey,
    CAST(NULLIF("multi-glaze-proportion", '') AS FLOAT) AS multi_glaze_proportion,
    CAST(tenure AS TEXT) AS tenure,
    CAST(posttown AS TEXT) AS posttown,
    CAST(uprn AS TEXT) AS uprn,
    CAST("mainheat-energy-eff" AS TEXT) AS mainheat_energy_eff,
    CAST("current-energy-rating" AS TEXT) AS current_energy_rating,
    CAST(postcode AS TEXT) AS postcode,
    CAST("mainheat-description" AS TEXT) AS mainheat_description,
    CAST("sheating-env-eff" AS TEXT) AS sheating_env_eff,
    CAST("walls-description" AS TEXT) AS walls_description,
    CAST(NULLIF("flat-storey-count", '') AS FLOAT) AS flat_storey_count,
    CAST("potential-energy-rating" AS TEXT) AS potential_energy_rating,
    CAST("hotwater-description" AS TEXT) AS hotwater_description,
    CAST(NULLIF("lighting-cost-current", '') AS FLOAT) AS lighting_cost_current,
    CAST(NULLIF("floor-height", '') AS FLOAT) AS floor_height,
    CAST(NULLIF("lighting-cost-potential", '') AS FLOAT) AS lighting_cost_potential,
    CAST("floor-energy-eff" AS TEXT) AS floor_energy_eff,
    CAST("windows-description" AS TEXT) AS windows_description,
    CAST("sheating-energy-eff" AS TEXT) AS sheating_energy_eff,
    CAST("energy-consumption-current" AS FLOAT) AS energy_consumption_current,
    CAST("potential-energy-efficiency" AS FLOAT) AS potential_energy_efficiency,
    CAST(NULLIF("heating-cost-current", '') AS FLOAT) AS heating_cost_current,
    CAST(NULLIF("hot-water-cost-current", '') AS FLOAT) AS hot_water_cost_current,
    CAST("construction-age-band" AS TEXT) AS construction_age_band,
    CAST("main-heating-controls" AS TEXT) AS main_heating_controls,
    CAST("solar-water-heating-flag" AS TEXT) AS solar_water_heating_flag,
    CAST("built-form" AS TEXT) AS built_form,
    CAST("property-type" AS TEXT) AS property_type,
    CAST(NULLIF("co2-emiss-curr-per-floor-area", '') AS FLOAT) AS co2_emiss_curr_per_floor_area,
    CAST("roof-energy-eff" AS TEXT) AS roof_energy_eff,
    CAST("lighting-env-eff" AS TEXT) AS lighting_env_eff,
    CAST(NULLIF("extension-count", '') AS FLOAT) AS extension_count,
    CAST("floor-level" AS TEXT) AS floor_level,
    CAST("lodgement-datetime" AS TEXT) AS lodgement_datetime,
    CAST("heat-loss-corridor" AS TEXT) AS heat_loss_corridor,
    CAST("mainheatc-env-eff" AS TEXT) AS mainheatc_env_eff,
    CAST("lighting-description" AS TEXT) AS lighting_description,
    CAST("windows-env-eff" AS TEXT) AS windows_env_eff,
    CAST("hot-water-energy-eff" AS TEXT) AS hot_water_energy_eff,
    CAST("transaction-type" AS TEXT) AS transaction_type,
    CAST("mainheatc-energy-eff" AS TEXT) AS mainheatc_energy_eff,
    CAST(NULLIF("co2-emissions-current", '') AS FLOAT) AS co2_emissions_current,
    CAST("local-authority-label" AS TEXT) AS local_authority_label,
    CAST(address AS TEXT) AS address,
    CAST(address1 AS TEXT) AS address1,
    CAST(address2 AS TEXT) AS address2,
    CAST(address3 AS TEXT) AS address3,
    CAST("roof-description" AS TEXT) AS roof_description,
    CAST("hot-water-env-eff" AS TEXT) AS hot_water_env_eff,
    CAST(NULLIF("environment-impact-current", '') AS FLOAT) AS environment_impact_current,
    CAST("energy-tariff" AS TEXT) AS energy_tariff,
    CAST(NULLIF("hot-water-cost-potential", '') AS FLOAT) AS hot_water_cost_potential,
    CAST("glazed-type" AS TEXT) AS glazed_type,
    CAST("lighting-energy-eff" AS TEXT) AS lighting_energy_eff,
    CAST(NULLIF("heating-cost-potential", '') AS FLOAT) AS heating_cost_potential,
    CAST("local-authority" AS TEXT) AS local_authority,
    CAST("constituency-label" AS TEXT) AS constituency_label,
    CAST("mainheatcont-description" AS TEXT) AS mainheatcont_description,
    CAST("building-reference-number" AS TEXT) AS building_reference_number,
    CAST(NULLIF("low-energy-lighting", '') AS INT) AS low_energy_lighting,
    CAST(NULLIF("unheated-corridor-length", '') AS FLOAT) AS unheated_corridor_length,
    CAST(constituency AS TEXT) AS constituency,
    CAST("floor-description" AS TEXT) AS floor_description,
    CAST(NULLIF("wind-turbine-count", '') AS INT) AS wind_turbine_count,
    CAST("inspection-date" AS DATE) AS inspection_date,
    CAST("uprn-source" AS TEXT) AS uprn_source,
    CAST("lodgement-date" AS DATE) AS lodgement_date,
    CAST(NULLIF("number-habitable-rooms", '') AS INT) AS number_habitable_rooms,
    _airbyte_ab_id,
    _airbyte_emitted_at,
    _airbyte_normalized_at,
    "_airbyte_england_wal__c_certificates_hashid" AS _airbyte_hashid,
    'domestic' AS certificate_type
FROM
    {{ source('postgres', 'england_wales_domestic_certificates') }}

UNION

SELECT
    -- England & Wales Non-Domestic
    CAST(NULL AS TEXT) AS walls_env_eff,
    CAST(NULL AS FLOAT) AS fixed_lighting_outlets_count,
    CAST('NO DATA!' AS TEXT) AS glazed_area,
    CAST(NULL AS FLOAT) AS energy_consumption_potential,
    CAST(NULL AS FLOAT) AS low_energy_fixed_light_count,
    CAST(NULL AS TEXT) AS secondheat_description,
    CAST("lmk-key" AS TEXT) AS lmk_key,
    CAST(county AS TEXT) AS county,
    CAST(NULL AS TEXT) AS main_fuel,
    CAST(NULL AS TEXT) AS mains_gas_flag,
    CAST(NULL AS INT) AS number_open_fireplaces,
    CAST(NULL AS FLOAT) AS co2_emissions_potential,
    CAST(NULL AS FLOAT) AS current_energy_efficiency,
    CAST(NULL AS TEXT) AS walls_energy_eff,
    CAST(NULL AS INT) AS number_heated_rooms,
    CAST(NULL AS TEXT) AS floor_env_eff,
    CAST(NULL AS TEXT) AS mechanical_ventilation,
    CAST(NULL AS FLOAT) AS photo_supply,
    CAST(NULL AS TEXT) AS mainheat_env_eff,
    CAST(NULL AS FLOAT) AS environment_impact_potential,
    CAST(NULL AS TEXT) AS windows_energy_eff,
    CAST(NULL AS TEXT) AS roof_env_eff,
    CAST(NULL AS FLOAT) AS total_floor_area,
    CAST(NULL AS TEXT) AS flat_top_storey,
    CAST(NULL AS FLOAT) AS multi_glaze_proportion,
    CAST(NULL AS TEXT) AS tenure,
    CAST(posttown AS TEXT) AS posttown,
    CAST(uprn AS TEXT) AS uprn,
    CAST(NULL AS TEXT) AS mainheat_energy_eff,
    CAST(NULL AS TEXT) AS current_energy_rating,
    CAST(postcode AS TEXT) AS postcode,
    CAST(NULL AS TEXT) AS mainheat_description,
    CAST(NULL AS TEXT) AS sheating_env_eff,
    CAST(NULL AS TEXT) AS walls_description,
    CAST(NULL AS FLOAT) AS flat_storey_count,
    CAST(NULL AS TEXT) AS potential_energy_rating,
    CAST(NULL AS TEXT) AS hotwater_description,
    CAST(NULL AS FLOAT) AS lighting_cost_current,
    CAST(NULL AS FLOAT) AS floor_height,
    CAST(NULL AS FLOAT) AS lighting_cost_potential,
    CAST(NULL AS TEXT) AS floor_energy_eff,
    CAST(NULL AS TEXT) AS windows_description,
    CAST(NULL AS TEXT) AS sheating_energy_eff,
    CAST(NULL AS FLOAT) AS energy_consumption_current,
    CAST(NULL AS FLOAT) AS potential_energy_efficiency,
    CAST(NULL AS FLOAT) AS heating_cost_current,
    CAST(NULL AS FLOAT) AS hot_water_cost_current,
    CAST(NULL AS TEXT) AS construction_age_band,
    CAST(NULL AS TEXT) AS main_heating_controls,
    CAST(NULL AS TEXT) AS solar_water_heating_flag,
    CAST(NULL AS TEXT) AS built_form,
    CAST("property-type" AS TEXT) AS property_type,
    CAST(NULL AS FLOAT) AS co2_emiss_curr_per_floor_area,
    CAST(NULL AS TEXT) AS roof_energy_eff,
    CAST(NULL AS TEXT) AS lighting_env_eff,
    CAST(NULL AS FLOAT) AS extension_count,
    CAST(NULL AS TEXT) AS floor_level,
    CAST("lodgement-datetime" AS TEXT) AS lodgement_datetime,
    CAST(NULL AS TEXT) AS heat_loss_corridor,
    CAST(NULL AS TEXT) AS mainheatc_env_eff,
    CAST(NULL AS TEXT) AS lighting_description,
    CAST(NULL AS TEXT) AS windows_env_eff,
    CAST(NULL AS TEXT) AS hot_water_energy_eff,
    CAST("transaction-type" AS TEXT) AS transaction_type,
    CAST(NULL AS TEXT) AS mainheatc_energy_eff,
    CAST(NULL AS FLOAT) AS co2_emissions_current,
    CAST("local-authority-label" AS TEXT) AS local_authority_label,
    CAST(address AS TEXT) AS address,
    CAST(address1 AS TEXT) AS address1,
    CAST(address2 AS TEXT) AS address2,
    CAST(address3 AS TEXT) AS address3,
    CAST(NULL AS TEXT) AS roof_description,
    CAST(NULL AS TEXT) AS hot_water_env_eff,
    CAST(NULL AS FLOAT) AS environment_impact_current,
    CAST(NULL AS TEXT) AS energy_tariff,
    CAST(NULL AS FLOAT) AS hot_water_cost_potential,
    CAST(NULL AS TEXT) AS glazed_type,
    CAST(NULL AS TEXT) AS lighting_energy_eff,
    CAST(NULL AS FLOAT) AS heating_cost_potential,
    CAST("local-authority" AS TEXT) AS local_authority,
    CAST("constituency-label" AS TEXT) AS constituency_label,
    CAST(NULL AS TEXT) AS mainheatcont_description,
    CAST("building-reference-number" AS TEXT) AS building_reference_number,
    CAST(NULL AS INT) AS low_energy_lighting,
    CAST(NULL AS FLOAT) AS unheated_corridor_length,
    CAST(constituency AS TEXT) AS constituency,
    CAST(NULL AS TEXT) AS floor_description,
    CAST(NULL AS INT) AS wind_turbine_count,
    CAST("inspection-date" AS DATE) AS inspection_date,
    CAST("uprn-source" AS TEXT) AS uprn_source,
    CAST("lodgement-date" AS DATE) AS lodgement_date,
    CAST(NULL AS INT) AS number_habitable_rooms,
    "_airbyte_ab_id",
    "_airbyte_emitted_at",
    "_airbyte_normalized_at",
    "_airbyte_england_wal__c_certificates_hashid" AS _airbyte_hashid,
    'non_domestic' AS certificate_type
FROM
    {{ source('postgres', 'england_wales_nondomestic_certificates') }}

UNION

(
    SELECT
        -- Scotland Domestic
        CAST(NULL AS TEXT) AS walls_env_eff,
        CAST("fixed_lighting_outlets_count" AS FLOAT) AS fixed_lighting_outlets_count,
        "glazed_area" AS glazed_area,
        CAST("energy_consumption_potential" AS FLOAT) AS energy_consumption_potential,
        CAST("low_energy_fixed_light_count" AS FLOAT) AS low_energy_fixed_light_count,
        "secondheat_description" AS secondheat_description,
        CAST(NULL AS TEXT) AS lmk_key,
        CAST(NULL AS TEXT) AS county,
        "main_fuel" AS main_fuel,
        "mains_gas_flag" AS mains_gas_flag,
        CAST("number_open_fireplaces" AS INT) AS number_open_fireplaces,
        CAST("co2_emissions_potential" AS FLOAT) AS co2_emissions_potential,
        CAST("current_energy_efficiency" AS INT) AS current_energy_efficiency,
        CAST(NULL AS TEXT) AS walls_energy_eff,
        CAST("number_heated_rooms" AS INT) AS number_heated_rooms,
        "floor_env_eff" AS floor_env_eff,
        "mechanical_ventilation" AS mechanical_ventilation,
        "photo_supply" AS photo_supply,
        "mainheat_env_eff" AS mainheat_env_eff,
        CAST("environment_impact_potential" AS FLOAT) AS environment_impact_potential,
        "windows_energy_eff" AS windows_energy_eff,

        CAST("building_reference_number" AS BIGINT) AS building_reference_number,
        "osg_reference_number" AS osg_reference_number,
        "address1" AS address1,
        "address2" AS address2,
        CAST("address3" AS TEXT) AS posttown,
        "postcode" AS postcode,
        TO_DATE("inspection_date", 'YYYY-MM-DD') AS inspection_date,
        TO_DATE("lodgement_date", 'YYYY-MM-DD') AS lodgement_date,
        "property_type" AS property_type,
        CAST("total_floor_area" AS TEXT) AS total_floor_area,
        CAST(NULL AS TEXT) AS current_energy_performance_rating,
        CAST(NULL AS TEXT) AS current_energy_performance_band,
        CAST(NULL AS TEXT) AS potential_energy_performance_rating,
        CAST(NULL AS TEXT) AS potential_energy_performance_band,
        "potential_energy_efficiency" AS potential_energy_efficiency,
        CAST(NULL AS INT) AS new_build_energy_performance_rating,
        CAST(NULL AS TEXT) AS new_build_energy_performance_band,
        CAST("environment_impact_current" AS FLOAT) AS environment_impact_current,
        CAST("co2_emiss_curr_per_floor_area" AS FLOAT) AS co2_emiss_curr_per_floor_area,
        CAST(NULL AS TEXT) AS current_environmental_performance_band,
        CAST(NULL AS TEXT) AS potential_environmental_performance_band,
        CAST(NULL AS TEXT) AS meets_2002_standard,
        CAST(NULL AS TEXT) AS asset_rating,
        CAST(NULL AS TEXT) AS asset_rating_band,
        CAST(NULL AS FLOAT) AS building_emissions,
        CAST(NULL AS TEXT) AS renewable_sources,
        CAST(NULL AS TEXT) AS electricity_source,
        CAST(NULL AS TEXT) AS main_heating_fuel,
        CAST(NULL AS TEXT) AS building_environment,
        CAST(NULL AS INT) AS primary_energy_value,
        CAST(NULL AS INT) AS approximate_energy_use,
        CAST(NULL AS TEXT) AS local_authority,
        "data_zone" AS data_zone,
        "constituency" AS constituency,
        "constituency_label" AS constituency_label,
        "transaction_type" AS transaction_type,
        CAST(NULL AS FLOAT) AS target_emissions,
        "data_zone_2011" AS data_zone_2011,
        "created_at" AS created_at,
        "wall_description" AS walls_description,
        "roof_description" AS roof_description,
        "roof_energy_eff" AS roof_energy_eff,
        "roof_env_eff" AS roof_env_eff,
        "floor_description" AS floor_description,
        "floor_energy_eff" AS floor_energy_eff,
        "windows_description" AS windows_description,
        "windows_env_eff" AS windows_env_eff,
        "mainheat_description" AS mainheat_description,
        "mainheat_energy_eff" AS mainheat_energy_eff,
        "mainheatcont_description" AS mainheatcont_description,
        "mainheatc_energy_eff" AS mainheatc_energy_eff,
        "mainheatc_env_eff" AS mainheatc_env_eff,
        "sheating_energy_eff" AS sheating_energy_eff,
        "sheating_env_eff" AS sheating_env_eff,
        "hotwater_description" AS hotwater_description,
        "hot_water_energy_eff" AS hot_water_energy_eff,
        "hot_water_env_eff" AS hot_water_env_eff,
        "lighting_description" AS lighting_description,
        "lighting_energy_eff" AS lighting_energy_eff,
        "lighting_env_eff" AS lighting_env_eff,
        "air_tightness_description" AS air_tightness_description,
        "air_tightness_energy_eff" AS air_tightness_energy_eff,
        "air_tightness_env_eff" AS air_tightness_env_eff,
        CAST("co2_emissions_current" AS FLOAT) AS co2_emissions_current,
        CAST("heating_cost_current" AS FLOAT) AS heating_cost_current,
        CAST("heating_cost_potential" AS FLOAT) AS heating_cost_potential,
        CAST("hot_water_cost_current" AS FLOAT) AS hot_water_cost_current,
        CAST("hot_water_cost_potential" AS FLOAT) AS hot_water_cost_potential,
        CAST("lighting_cost_current" AS FLOAT) AS lighting_cost_current,
        CAST("lighting_cost_potential" AS FLOAT) AS lighting_cost_potential,
        CAST("energy_consumption_current" AS FLOAT) AS energy_consumption_current,
        "space_heating_demand" AS space_heating_demand,
        CAST("lzc_energy_sources" AS TEXT) AS lzc_energy_sources,
        "water_heating_demand" AS water_heating_demand,
        "impact_loft_insulation" AS impact_loft_insulation,
        "impact_cavity_wall_insulation" AS impact_cavity_wall_insulation,
        "impact_solid_wall_insulation" AS impact_solid_wall_insulation,
        "construction_age_band" AS construction_age_band,
        CAST("floor_height" AS FLOAT) AS floor_height,
        CAST("extension_count" AS INT) AS extension_count,
        CAST("low_energy_lighting" AS FLOAT) AS low_energy_lighting,
        "floor_level" AS floor_level,
        "flat_top_storey" AS flat_top_storey,
        CAST("number_habitable_rooms" AS INT) AS number_habitable_rooms,
        "heat_loss_corridoor" AS heat_loss_corridor,
        "local_authority_label" AS local_authority_label,
        "main_heating_category" AS main_heating_category,
        "main_heating_controls" AS main_heating_controls,
        "energy_tariff" AS energy_tariff,
        "multi_glaze_proportion" AS multi_glaze_proportion,
        "glazed_type" AS glazed_type,
        "solar_water_heating_flag" AS solar_water_heating_flag,
        "tenure" AS tenure,
        CAST("unheated_corridor_length" AS FLOAT) AS unheated_corridor_length,
        "built_form" AS built_form,
        CAST("wind_turbine_count" AS INT) AS wind_turbine_count,
        CAST(NULL AS FLOAT) AS three_year_energy_savings_potential,
        CAST("3_YR_ENERGY_COST_CURRENT" AS FLOAT) AS three_year_energy_cost_current,
        "type_of_assessment" AS type_of_assessment,
        'domestic' AS certificate_type
    FROM {{ source('postgres', 'scotland_certificates_domestic') }}
)

UNION

(
    SELECT
        -- Scotland Non-Domestic
        CAST(NULL AS TEXT) AS walls_env_eff,
        CAST(NULL AS FLOAT) AS fixed_lighting_outlets_count,
        CAST(NULL AS TEXT) AS glazed_area,
        CAST(NULL AS FLOAT) AS energy_consumption_potential,
        CAST(NULL AS FLOAT) AS low_energy_fixed_light_count,
        CAST(NULL AS TEXT) AS secondheat_description,
        CAST(NULL AS TEXT) AS lmk_key,
        CAST(NULL AS TEXT) AS county,
        CAST(NULL AS TEXT) AS main_fuel,
        CAST(NULL AS TEXT) AS mains_gas_flag,
        CAST(NULL AS INT) AS number_open_fireplaces,
        CAST(NULL AS FLOAT) AS co2_emissions_potential,
        CAST(NULL AS INT) AS current_energy_efficiency,
        CAST(NULL AS TEXT) AS walls_energy_eff,
        CAST(NULL AS INT) AS number_heated_rooms,
        CAST(NULL AS TEXT) AS floor_env_eff,
        CAST(NULL AS TEXT) AS mechanical_ventilation,
        CAST(NULL AS TEXT) AS photo_supply,
        CAST(NULL AS TEXT) AS mainheat_env_eff,
        CAST(NULL AS FLOAT) AS environment_impact_potential,
        CAST(NULL AS TEXT) AS windows_energy_eff,

        CAST("building_reference_number" AS BIGINT) AS building_reference_number,
        "osg_reference_number" AS osg_reference_number,
        "address1" AS address1,
        "address2" AS address2,
        CAST("post_town" AS TEXT) AS posttown,
        "postcode" AS postcode,
        TO_DATE("inspection_date", 'yyyy-mm-dd') AS inspection_date,
        TO_DATE("lodgement_date", 'yyyy-mm-dd') AS lodgement_date,
        "property_type" AS property_type,
        CAST("floor_area" AS TEXT) AS total_floor_area,
        "current_energy_performance_rating" AS current_energy_performance_rating,
        CAST("current_energy_performance_band" AS TEXT) AS current_energy_performance_band,
        "potential_energy_performance_rating" AS potential_energy_performance_rating,
        "potential_energy_performance_band" AS potential_energy_performance_band,
        CAST(NULL AS TEXT) AS potential_energy_efficiency,
        CAST(
            NULLIF("new_build_energy_performance_rating", '') AS INT
        ) AS new_build_energy_performance_rating,
        "new_build_energy_performance_band" AS new_build_energy_performance_band,
        CAST(NULL AS FLOAT) AS environment_impact_current,
        CAST(NULL AS FLOAT) AS co2_emiss_curr_per_floor_area,
        CAST(NULL AS TEXT) AS current_environmental_performance_band,
        CAST(NULL AS TEXT) AS potential_environmental_performance_band,
        "meets_2002_standard" AS meets_2002_standard,
        "asset_rating" AS asset_rating,
        "asset_rating_band" AS asset_rating_band,
        CAST("building_emissions" AS FLOAT) AS building_emissions,
        "renewable_sources" AS renewable_sources,
        "electricity_source" AS electricity_source,
        "main_heating_fuel" AS main_heating_fuel,
        "building_environment" AS building_environment,
        CAST("primary_energy_value" AS INT) AS primary_energy_value,
        CAST("approximate_energy_use" AS INT) AS approximate_energy_use,
        "local_authority" AS local_authority,
        "data_zone" AS data_zone,
        "constituency" AS constituency,
        "constituency_label" AS constituency_label,
        "transaction_type" AS transaction_type,
        CAST("target_emissions" AS FLOAT) AS target_emissions,
        "data_zone_2011" AS data_zone_2011,
        "created_at" AS created_at,
        CAST(NULL AS TEXT) AS walls_description,
        CAST(NULL AS TEXT) AS roof_description,
        CAST(NULL AS TEXT) AS roof_energy_eff,
        CAST(NULL AS TEXT) AS roof_env_eff,
        CAST(NULL AS TEXT) AS floor_description,
        CAST(NULL AS TEXT) AS floor_energy_eff,
        CAST(NULL AS TEXT) AS windows_description,
        CAST(NULL AS TEXT) AS windows_env_eff,
        CAST(NULL AS TEXT) AS mainheat_description,
        CAST(NULL AS TEXT) AS mainheat_energy_eff,
        CAST(NULL AS TEXT) AS mainheatcont_description,
        CAST(NULL AS TEXT) AS mainheatc_energy_eff,
        CAST(NULL AS TEXT) AS mainheatc_env_eff,
        CAST(NULL AS TEXT) AS sheating_energy_eff,
        CAST(NULL AS TEXT) AS sheating_env_eff,
        CAST(NULL AS TEXT) AS hotwater_description,
        CAST(NULL AS TEXT) AS hot_water_energy_eff,
        CAST(NULL AS TEXT) AS hot_water_env_eff,
        CAST(NULL AS TEXT) AS lighting_description,
        CAST(NULL AS TEXT) AS lighting_energy_eff,
        CAST(NULL AS TEXT) AS lighting_env_eff,
        CAST(NULL AS TEXT) AS air_tightness_env_eff,
        CAST(NULL AS TEXT) AS air_tightness_description,
        CAST(NULL AS TEXT) AS air_tightness_energy_eff,
        CAST(NULL AS FLOAT) AS co2_emissions_current,
        CAST(NULL AS FLOAT) AS heating_cost_current,
        CAST(NULL AS FLOAT) AS heating_cost_potential,
        CAST(NULL AS FLOAT) AS hot_water_cost_current,
        CAST(NULL AS FLOAT) AS hot_water_cost_potential,
        CAST(NULL AS FLOAT) AS lighting_cost_current,
        CAST(NULL AS FLOAT) AS lighting_cost_potential,
        CAST(NULL AS FLOAT) AS energy_consumption_current,
        CAST(NULL AS TEXT) AS lzc_energy_sources,
        CAST(NULL AS TEXT) AS space_heating_demand,
        CAST(NULL AS TEXT) AS water_heating_demand,
        CAST(NULL AS TEXT) AS impact_loft_insulation,
        CAST(NULL AS TEXT) AS impact_cavity_wall_insulation,
        CAST(NULL AS TEXT) AS impact_solid_wall_insulation,
        CAST(NULL AS TEXT) AS construction_age_band,
        CAST(NULL AS FLOAT) AS floor_height,
        CAST(NULL AS INT) AS extension_count,
        CAST(NULL AS FLOAT) AS low_energy_lighting,
        CAST(NULL AS TEXT) AS floor_level,
        CAST(NULL AS TEXT) AS flat_top_storey,
        CAST(NULL AS INT) AS number_habitable_rooms,
        CAST(NULL AS TEXT) AS heat_loss_corridor,
        CAST(NULL AS TEXT) AS local_authority_label,
        CAST(NULL AS TEXT) AS main_heating_category,
        CAST(NULL AS TEXT) AS main_heating_controls,
        CAST(NULL AS TEXT) AS energy_tariff,
        CAST(NULL AS TEXT) AS multi_glaze_proportion,
        CAST(NULL AS TEXT) AS glazed_type,
        CAST(NULL AS TEXT) AS solar_water_heating_flag,
        CAST(NULL AS TEXT) AS tenure,
        CAST(NULL AS FLOAT) AS unheated_corridor_length,
        CAST(NULL AS TEXT) AS built_form,
        CAST(NULL AS INT) AS wind_turbine_count,
        CAST(NULL AS FLOAT) AS three_year_energy_cost_current,
        CAST(NULL AS FLOAT) AS three_year_energy_savings_potential,
        CAST(NULL AS TEXT) AS type_of_assessment,
        'non-domestic' AS certificate_type

    FROM {{ source('postgres', 'scotland_certificates_non_domestic') }}
)
