{{ config(materialized='table') }}
(
    SELECT
        CAST("BUILDING_REFERENCE_NUMBER" AS BIGINT) AS building_reference_number,
        "OSG_REFERENCE_NUMBER" AS osg_reference_number,
        "ADDRESS1" AS address1,
        "ADDRESS2" AS address2,
        CAST("POST_TOWN" AS TEXT) AS posttown,
        "POSTCODE" AS postcode,
        TO_DATE("INSPECTION_DATE", 'YYYY-MM-DD') AS inspection_date,
        TO_DATE("LODGEMENT_DATE", 'YYYY-MM-DD') AS lodgement_date,
        "PROPERTY_TYPE" AS property_type,
        CAST("FLOOR_AREA" AS TEXT) AS total_floor_area,
        "CURRENT_ENERGY_PERFORMANCE_RATING" AS current_energy_performance_rating,
        CAST("CURRENT_ENERGY_PERFORMANCE_BAND" AS TEXT) AS current_energy_performance_band,
        CAST(NULL AS INT) AS current_energy_efficiency,
        "POTENTIAL_ENERGY_PERFORMANCE_RATING" AS potential_energy_performance_rating,
        "POTENTIAL_ENERGY_PERFORMANCE_BAND" AS potential_energy_performance_band,
        CAST(NULL AS TEXT) AS potential_energy_efficiency,
        CAST(
            NULLIF("NEW_BUILD_ENERGY_PERFORMANCE_RATING", '') AS INT
        ) AS new_build_energy_performance_rating,
        "NEW_BUILD_ENERGY_PERFORMANCE_BAND" AS new_build_energy_performance_band,
        CAST(NULL AS FLOAT) AS environment_impact_current,
        CAST(NULL AS FLOAT) AS environment_impact_potential,
        CAST(NULL AS FLOAT) AS co2_emiss_curr_per_floor_area,
        CAST(NULL AS TEXT) AS current_environmental_performance_band,
        CAST(NULL AS TEXT) AS potential_environmental_performance_band,
        "MEETS_2002_STANDARD" AS meets_2002_standard,
        "ASSET_RATING" AS asset_rating,
        "ASSET_RATING_BAND" AS asset_rating_band,
        CAST("BUILDING_EMISSIONS" AS FLOAT) AS building_emissions,
        "RENEWABLE_SOURCES" AS renewable_sources,
        "ELECTRICITY_SOURCE" AS electricity_source,
        "MAIN_HEATING_FUEL" AS main_heating_fuel,
        "BUILDING_ENVIRONMENT" AS building_environment,
        CAST("PRIMARY_ENERGY_VALUE" AS INT) AS primary_energy_value,
        CAST("APPROXIMATE_ENERGY_USE" AS INT) AS approximate_energy_use,
        "LOCAL_AUTHORITY" AS local_authority,
        "DATA_ZONE" AS data_zone,
        "CONSTITUENCY" AS constituency,
        "CONSTITUENCY_LABEL" AS constituency_label,
        "TRANSACTION_TYPE" AS transaction_type,
        CAST("TARGET_EMISSIONS" AS FLOAT) AS target_emissions,
        "DATA_ZONE_2011" AS data_zone_2011,
        "CREATED_AT" AS created_at,
        CAST(NULL AS TEXT) AS wall_description,
        CAST(NULL AS TEXT) AS wall_energy_eff,
        CAST(NULL AS TEXT) AS walL_env_eff,
        CAST(NULL AS TEXT) AS roof_description,
        CAST(NULL AS TEXT) AS roof_energy_eff,
        CAST(NULL AS TEXT) AS roof_env_eff,
        CAST(NULL AS TEXT) AS floor_description,
        CAST(NULL AS TEXT) AS floor_energy_eff,
        CAST(NULL AS TEXT) AS floor_env_eff,
        CAST(NULL AS TEXT) AS windows_description,
        CAST(NULL AS TEXT) AS windows_energy_eff,
        CAST(NULL AS TEXT) AS windows_env_eff,
        CAST(NULL AS TEXT) AS mainheat_description,
        CAST(NULL AS TEXT) AS mainheat_energy_eff,
        CAST(NULL AS TEXT) AS mainheat_env_eff,
        CAST(NULL AS TEXT) AS mainheatcont_description,
        CAST(NULL AS TEXT) AS mainheatc_energy_eff,
        CAST(NULL AS TEXT) AS mainheatc_env_eff,
        CAST(NULL AS TEXT) AS secondheat_description,
        CAST(NULL AS TEXT) AS sheating_energy_eff,
        CAST(NULL AS TEXT) AS sheating_env_eff,
        CAST(NULL AS TEXT) AS hotwater_description,
        CAST(NULL AS TEXT) AS hot_water_energy_eff,
        CAST(NULL AS TEXT) AS hot_water_env_eff,
        CAST(NULL AS TEXT) AS lighting_description,
        CAST(NULL AS TEXT) AS lighting_energy_eff,
        CAST(NULL AS TEXT) AS lighting_env_eff,
        CAST(NULL AS TEXT) AS air_tightness_env_eff,
        CAST(NULL AS TEXT) AS air_tightness_description,
        CAST(NULL AS TEXT) AS air_tightness_energy_eff,
        CAST(NULL AS FLOAT) AS co2_emissions_current,
        CAST(NULL AS FLOAT) AS co2_emissions_potential,
        CAST(NULL AS FLOAT) AS heating_cost_current,
        CAST(NULL AS FLOAT) AS heating_cost_potential,
        CAST(NULL AS FLOAT) AS hot_water_cost_current,
        CAST(NULL AS FLOAT) AS hot_water_cost_potential,
        CAST(NULL AS FLOAT) AS lighting_cost_current,
        CAST(NULL AS FLOAT) AS lighting_cost_potential,
        CAST(NULL AS FLOAT) AS energy_consumption_current,
        CAST(NULL AS FLOAT) AS energy_consumption_potential,
        CAST(NULL AS TEXT) AS lzc_energy_sources,
        CAST(NULL AS TEXT) AS space_heating_demand,
        CAST(NULL AS TEXT) AS water_heating_demand,
        CAST(NULL AS TEXT) AS impact_loft_insulation,
        CAST(NULL AS TEXT) AS impact_cavity_wall_insulation,
        CAST(NULL AS TEXT) AS impact_solid_wall_insulation,
        CAST(NULL AS TEXT) AS construction_age_band,
        CAST(NULL AS FLOAT) AS floor_height,
        CAST(NULL AS INT) AS extension_count,
        CAST(NULL AS FLOAT) AS fixed_lighting_outlets_count,
        CAST(NULL AS FLOAT) AS low_energy_fixed_light_count,
        CAST(NULL AS FLOAT) AS low_energy_lighting,
        CAST(NULL AS TEXT) AS floor_level,
        CAST(NULL AS TEXT) AS flat_top_storey,
        CAST(NULL AS TEXT) AS glazed_area,
        CAST(NULL AS INT) AS number_habitable_rooms,
        CAST(NULL AS TEXT) AS heat_loss_corridor,
        CAST(NULL AS INT) AS number_heated_rooms,
        CAST(NULL AS TEXT) AS local_authority_label,
        CAST(NULL AS TEXT) AS mains_gas_flag,
        CAST(NULL AS TEXT) AS main_heating_category,
        CAST(NULL AS TEXT) AS main_heating_controls,
        CAST(NULL AS TEXT) AS main_fuel,
        CAST(NULL AS TEXT) AS mechanical_ventilation,
        CAST(NULL AS TEXT) AS energy_tariff,
        CAST(NULL AS TEXT) AS multi_glaze_proportion,
        CAST(NULL AS TEXT) AS glazed_type,
        CAST(NULL AS INT) AS number_open_fireplaces,
        CAST(NULL AS TEXT) AS photo_supply,
        CAST(NULL AS TEXT) AS solar_water_heating_flag,
        CAST(NULL AS TEXT) AS tenure,
        CAST(NULL AS FLOAT) AS unheated_corridor_length,
        CAST(NULL AS TEXT) AS built_form,
        CAST(NULL AS INT) AS wind_turbine_count,
        CAST(NULL AS FLOAT) AS three_year_energy_cost_current,
        CAST(NULL AS FLOAT) AS three_year_energy_savings_potential,
        CAST(NULL AS TEXT) AS type_of_assessment,
        'non-domestic' AS certificate_type

    FROM {{ source('postgres', 'scotland_nondomestic_certificates') }}
    -- WHERE LOWER(CAST("POST_TOWN" AS TEXT)) LIKE '%aberdeen'
)
UNION
(
    SELECT
        CAST("BUILDING_REFERENCE_NUMBER" AS BIGINT) AS building_reference_number,
        "OSG_REFERENCE_NUMBER" AS osg_reference_number,
        "ADDRESS1" AS address1,
        "ADDRESS2" AS address2,
        CAST("ADDRESS3" AS TEXT) AS posttown,
        "POSTCODE" AS postcode,
        TO_DATE("INSPECTION_DATE", 'YYYY-MM-DD') AS inspection_date,
        TO_DATE("LODGEMENT_DATE", 'YYYY-MM-DD') AS lodgement_date,
        "PROPERTY_TYPE" AS property_type,
        CAST("TOTAL_FLOOR_AREA" AS TEXT) AS total_floor_area,
        CAST(NULL AS TEXT) AS current_energy_performance_rating,
        CAST("CURRENT_ENERGY_RATING" AS TEXT) AS current_energy_performance_band,
        CAST("CURRENT_ENERGY_EFFICIENCY" AS INT) AS current_energy_efficiency,
        CAST(NULL AS TEXT) AS potential_energy_performance_rating,
        "POTENTIAL_ENERGY_RATING" AS potential_energy_performance_band,
        "POTENTIAL_ENERGY_EFFICIENCY" AS potential_energy_efficiency,
        CAST(NULL AS INT) AS new_build_energy_performance_rating,
        CAST(NULL AS TEXT) AS new_build_energy_performance_band,
        CAST("ENVIRONMENT_IMPACT_CURRENT" AS FLOAT) AS environment_impact_current,
        CAST("ENVIRONMENT_IMPACT_POTENTIAL" AS FLOAT) AS environment_impact_potential,
        CAST("CO2_EMISS_CURR_PER_FLOOR_AREA" AS FLOAT) AS co2_emiss_curr_per_floor_area,
        "CURRENT_ENVIRONMENTAL_RATING" AS current_environmental_performance_band,
        "POTENTIAL_ENVIRONMENTAL_RATING" AS potential_environmental_performance_band,
        CAST(NULL AS TEXT) AS meets_2002_standard,
        CAST(NULL AS TEXT) AS asset_rating,
        CAST(NULL AS TEXT) AS asset_rating_band,
        CAST(NULL AS FLOAT) AS building_emissions,
        CAST(NULL AS TEXT) AS renewable_sources,
        CAST(NULL AS TEXT) AS electricity_source,
        CAST(NULL AS TEXT) AS main_heating_fuel,
        CAST(NULL AS TEXT) AS building_environment,
        CAST(NULL AS INT) AS primary_energy_value,
        CAST(NULL AS INT) AS approximate_energy_use,
        CAST(NULL AS TEXT) AS local_authority,
        "DATA_ZONE" AS data_zone,
        "CONSTITUENCY" AS constituency,
        "CONSTITUENCY_LABEL" AS constituency_label,
        "TRANSACTION_TYPE" AS transaction_type,
        CAST(NULL AS FLOAT) AS target_emissions,
        "DATA_ZONE_2011" AS data_zone_2011,
        "CREATED_AT " AS created_at,
        "WALL_DESCRIPTION" AS wall_description,
        "WALL_ENERGY_EFF" AS wall_energy_eff,
        "WALL_ENV_EFF" AS wall_env_eff,
        "ROOF_DESCRIPTION" AS roof_description,
        "ROOF_ENERGY_EFF" AS roof_energy_eff,
        "ROOF_ENV_EFF" AS roof_env_eff,
        "FLOOR_DESCRIPTION" AS floor_description,
        "FLOOR_ENERGY_EFF" AS floor_energy_eff,
        "FLOOR_ENV_EFF" AS floor_env_eff,
        "WINDOWS_DESCRIPTION" AS windows_description,
        "WINDOWS_ENERGY_EFF" AS windows_energy_eff,
        "WINDOWS_ENV_EFF" AS windows_env_eff,
        "MAINHEAT_DESCRIPTION" AS mainheat_description,
        "MAINHEAT_ENERGY_EFF" AS mainheat_energy_eff,
        "MAINHEAT_ENV_EFF" AS mainheat_env_eff,
        "MAINHEATCONT_DESCRIPTION" AS mainheatcont_description,
        "MAINHEATC_ENERGY_EFF" AS mainheatc_energy_eff,
        "MAINHEATC_ENV_EFF" AS mainheatc_env_eff,
        "SECONDHEAT_DESCRIPTION" AS secondheat_description,
        "SHEATING_ENERGY_EFF" AS sheating_energy_eff,
        "SHEATING_ENV_EFF" AS sheating_env_eff,
        "HOTWATER_DESCRIPTION" AS hotwater_description,
        "HOT_WATER_ENERGY_EFF" AS hot_water_energy_eff,
        "HOT_WATER_ENV_EFF" AS hot_water_env_eff,
        "LIGHTING_DESCRIPTION" AS lighting_description,
        "LIGHTING_ENERGY_EFF" AS lighting_energy_eff,
        "LIGHTING_ENV_EFF" AS lighting_env_eff,
        "AIR_TIGHTNESS_DESCRIPTION" AS air_tightness_description,
        "AIR_TIGHTNESS_ENERGY_EFF" AS air_tightness_energy_eff,
        "AIR_TIGHTNESS_ENV_EFF" AS air_tightness_env_eff,
        CAST("CO2_EMISSIONS_CURRENT" AS FLOAT) AS co2_emissions_current,
        CAST("CO2_EMISSIONS_POTENTIAL" AS FLOAT) AS co2_emissions_potential,
        CAST("HEATING_COST_CURRENT" AS FLOAT) AS heating_cost_current,
        CAST("HEATING_COST_POTENTIAL" AS FLOAT) AS heating_cost_potential,
        CAST("HOT_WATER_COST_CURRENT" AS FLOAT) AS hot_water_cost_current,
        CAST("HOT_WATER_COST_POTENTIAL" AS FLOAT) AS hot_water_cost_potential,
        CAST("LIGHTING_COST_CURRENT" AS FLOAT) AS lighting_cost_current,
        CAST("LIGHTING_COST_POTENTIAL" AS FLOAT) AS lighting_cost_potential,
        CAST("ENERGY_CONSUMPTION_POTENTIAL" AS FLOAT) AS energy_consumption_potential,
        CAST("ENERGY_CONSUMPTION_CURRENT" AS FLOAT) AS energy_consumption_current,
        "SPACE_HEATING_DEMAND" AS space_heating_demand,
        CAST("LZC_ENERGY_SOURCES" AS TEXT) AS lzc_energy_sources,
        "WATER_HEATING_DEMAND" AS water_heating_demand,
        "IMPACT_LOFT_INSULATION" AS impact_loft_insulation,
        "IMPACT_CAVITY_WALL_INSULATION" AS impact_cavity_wall_insulation,
        "IMPACT_SOLID_WALL_INSULATION" AS impact_solid_wall_insulation,
        "CONSTRUCTION_AGE_BAND" AS construction_age_band,
        CAST("FLOOR_HEIGHT" AS FLOAT) AS floor_height,
        CAST("EXTENSION_COUNT" AS INT) AS extension_count,
        CAST("FIXED_LIGHTING_OUTLETS_COUNT" AS FLOAT) AS fixed_lighting_outlets_count,
        CAST("LOW_ENERGY_FIXED_LIGHT_COUNT" AS FLOAT) AS low_energy_fixed_light_count,
        CAST("LOW_ENERGY_LIGHTING" AS FLOAT) AS low_energy_lighting,
        "FLOOR_LEVEL" AS floor_level,
        "FLAT_TOP_STOREY" AS flat_top_storey,
        "GLAZED_AREA" AS glazed_area,
        CAST("NUMBER_HABITABLE_ROOMS" AS INT) AS number_habitable_rooms,
        "HEAT_LOSS_CORRIDOOR" AS heat_loss_corridor,
        CAST("NUMBER_HEATED_ROOMS" AS INT) AS number_heated_rooms,
        "LOCAL_AUTHORITY_LABEL" AS local_authority_label,
        "MAINS_GAS_FLAG" AS mains_gas_flag,
        "MAIN_HEATING_CATEGORY" AS main_heating_category,
        "MAIN_HEATING_CONTROLS" AS main_heating_controls,
        "MAIN_FUEL" AS main_fuel,
        "MECHANICAL_VENTILATION" AS mechanical_ventilation,
        "ENERGY_TARIFF" AS energy_tariff,
        "MULTI_GLAZE_PROPORTION" AS multi_glaze_proportion,
        "GLAZED_TYPE" AS glazed_type,
        CAST("NUMBER_OPEN_FIREPLACES" AS INT) AS number_open_fireplaces,
        "PHOTO_SUPPLY" AS photo_supply,
        "SOLAR_WATER_HEATING_FLAG" AS solar_water_heating_flag,
        "TENURE" AS tenure,
        CAST("UNHEATED_CORRIDOR_LENGTH" AS FLOAT) AS unheated_corridor_length,
        "BUILT_FORM" AS built_form,
        CAST("WIND_TURBINE_COUNT" AS INT) AS wind_turbine_count,
        CAST("3_YR_ENERGY_SAVINGS_POTENTIAL" AS FLOAT) AS three_year_energy_savings_potential,
        CAST("3_YR_ENERGY_COST_CURRENT" AS FLOAT) AS three_year_energy_cost_current,
        "TYPE_OF_ASSESSMENT" AS type_of_assessment,
        'domestic' AS certificate_type
    FROM {{ source('postgres', 'scotland_domestic_certificates') }}
    -- WHERE LOWER(CAST("ADDRESS3" AS TEXT)) LIKE '%aberdeen'
)
