{{ config(materialized='view') }}

select
    lmk_key,
    postcode,
    current_energy_rating,
    current_energy_efficiency,
    property_type,
    built_form,
    inspection_date,
    lodgement_date,
    environment_impact_current,
    co2_emissions_current,
    lighting_cost_current,
    heating_cost_current,
    hot_water_cost_current,
    total_floor_area,
    floor_level,
    flat_storey_count,
    main_heating_controls,
    glazed_type,
    number_open_fireplaces,
    floor_description,
    windows_description,
    walls_description,
    roof_description,
    mainheat_description,
    main_fuel,
    wind_turbine_count,
    mechanical_ventilation,
    address,
    posttown,
    construction_age_band,
    uprn,
    certificate_type
from {{ ref('stg_epc_certificates') }}
