{{ config(materialized='view') }}

-- Split multi-part descriptions into raw components for downstream mapping.

select
    lmk_key,
    uprn,
    address,
    postcode,
    property_type,
    built_form,
    current_energy_rating,
    current_energy_efficiency,
    roof_description,
    nullif(trim(split_part(roof_description, ',', 1)), '') as roof_construction_raw,
    nullif(trim(split_part(roof_description, ',', 2)), '') as roof_insulation_raw,
    nullif(trim(split_part(roof_description, ',', 3)), '') as roof_insulation_extra,
    walls_description,
    nullif(trim(split_part(walls_description, ',', 1)), '') as wall_construction_raw,
    nullif(trim(split_part(walls_description, ',', 2)), '') as wall_insulation_raw,
    nullif(trim(split_part(walls_description, ',', 3)), '') as wall_insulation_thickness_raw,
    floor_description,
    nullif(trim(split_part(floor_description, ',', 1)), '') as floor_construction_raw,
    nullif(trim(split_part(floor_description, ',', 2)), '') as floor_insulation_raw,
    nullif(trim(split_part(floor_description, ',', 3)), '') as floor_insulation_thickness_raw,
    windows_description,
    glazed_type,
    total_floor_area,
    environment_impact_current,
    lodgement_date,
    co2_emissions_current,
    floor_level,
    heating_cost_current,
    construction_age_band,
    main_heating_controls,
    mainheat_description,
    main_fuel,
    number_open_fireplaces,
    wind_turbine_count,
    mechanical_ventilation,
    hot_water_cost_current,
    lighting_cost_current,
    inspection_date,
    flat_storey_count,
    posttown,
    certificate_type
from {{ ref('int_epc_address_clean') }}
