{{ config(materialized = 'table') }}

(
SELECT
    "RPC" AS rpc,
    "POSTCODE" AS postcode,
    "LOGICAL_STATUS_CODE" AS logical_status_code,
    "COUNTRY_CODE_DESCRIPTION" AS country_code_description,
    "X_COORDINATE" AS x_coordinate,
    "LAST_UPDATE_DATE" AS last_update_date,
    "CLASSIFICATION_CODE_DESCRIPTION" AS classification_code_description,
    "ORGANISATION_NAME" AS organisation_name,
    "UDPRN" AS udprn,
    "STATUS" AS status,
    "PARENT_UPRN" AS parent_uprn,
    "POSTAL_ADDRESS_CODE" AS postal_address_code,
    "LOCAL_CUSTODIAN_CODE_DESCRIPTION" AS local_custodian_code_description,
    "DELIVERY_POINT_SUFFIX" AS delivery_point_suffix,
    "BUILDING_NUMBER" AS building_number,
    "THOROUGHFARE_NAME" AS thoroughfare_name,
    "LANGUAGE" AS language,
    "DEPENDENT_LOCALITY" AS dependent_locality,
    "BLPU_STATE_CODE_DESCRIPTION" AS blpu_state_code_description,
    "BLPU_STATE_CODE" AS blpu_state_code,
    "LOCAL_CUSTODIAN_CODE" AS local_custodian_code,
    "BLPU_STATE_DATE" AS blpu_state_date,
    "DEPENDENT_THOROUGHFARE_NAME" AS dependent_thoroughfare_name,
    "POST_TOWN" AS post_town,
    "BUILDING_NAME" AS building_name,
    "SUB_BUILDING_NAME" AS sub_building_name,
    "POSTAL_ADDRESS_CODE_DESCRIPTION" AS postal_address_code_description,
    "UPRN" AS uprn,
    "TOPOGRAPHY_LAYER_TOID" AS topography_layer_toid,
    "ADDRESS" AS address,
    "Y_COORDINATE" AS y_coordinate,
    "MATCH_DESCRIPTION" AS match_description,
    "CLASSIFICATION_CODE" AS classification_code,
    "ENTRY_DATE" AS entry_date,
    "MATCH" AS match,
    "COUNTRY_CODE" AS country_code,
    _airbyte_raw_id,
    _airbyte_extracted_at,
    _airbyte_generation_id,
    _airbyte_meta,
    'DPA' AS os_api_source

FROM {{ source('postgres', 'os_places_dpa') }}
)

UNION

(
SELECT
    "RPC" AS rpc,
    "POSTCODE_LOCATOR" AS postcode,
    "LOGICAL_STATUS_CODE" AS logical_status_code,
    "COUNTRY_CODE_DESCRIPTION" AS country_code_description,
    "X_COORDINATE" AS x_coordinate,
    "LAST_UPDATE_DATE" AS last_update_date,
    "CLASSIFICATION_CODE_DESCRIPTION" AS classification_code_description,
    'N/A' AS organisation_name,
    'N/A' AS udprn,
    "STATUS" AS status,
    "PARENT_UPRN" AS parent_uprn,
    "POSTAL_ADDRESS_CODE" AS postal_address_code,
    "LOCAL_CUSTODIAN_CODE_DESCRIPTION" AS local_custodian_code_description,
    'N/A' AS delivery_point_suffix,
    'N/A' AS building_number,
    'N/A' AS thoroughfare_name,
    "LANGUAGE" AS language,
    'N/A' AS dependent_locality,
    "BLPU_STATE_CODE_DESCRIPTION" AS blpu_state_code_description,
    "BLPU_STATE_CODE" AS blpu_state_code,
    "LOCAL_CUSTODIAN_CODE" AS local_custodian_code,
    "BLPU_STATE_DATE" AS blpu_state_date,
    'N/A' AS dependent_thoroughfare_name,
    'N/A' AS post_town,
    'N/A' AS building_name,
    'N/A' AS sub_building_name,
    "POSTAL_ADDRESS_CODE_DESCRIPTION" AS postal_address_code_description,
    "UPRN" AS uprn,
    "TOPOGRAPHY_LAYER_TOID" AS topography_layer_toid,
    "ADDRESS" AS address,
    "Y_COORDINATE" AS y_coordinate,
    "MATCH_DESCRIPTION" AS match_description,
    "CLASSIFICATION_CODE" AS classification_code,
    "ENTRY_DATE" AS entry_date,
    "MATCH" AS match,
    "COUNTRY_CODE" AS country_code,
    _airbyte_raw_id,
    _airbyte_extracted_at,
    _airbyte_generation_id,
    _airbyte_meta,
    'LPI' AS os_api_source

FROM {{ source('postgres', 'os_places_lpi') }}
WHERE "CLASSIFICATION_CODE_DESCRIPTION" NOT IN (
    'STREET RECORD',
    'PROPERTY SHELL',
    'STATIC WATER',
    'ELECTRICITY SUB-STATION',
    'POSTAL BOX',
    'BUS SHELTER',
    'ADDITIONAL MAIL / PACKET ADDRESSEE',
    'HOPPER / SILO / CISTERN / TANK',
    'GENERAL STORAGE LAND',
    'TELECOMMUNICATION',
    'HOUSE BOAT',
    'EQUESTRIAN',
    'TELEPHONE BOX',
    'PO BOX',
    'ADVERTISING HOARDING',
    'ALLOCATED PARKING'
)
)
