iris_data_cleansing:
  target: dev_with_fal
  outputs:
    dev_with_fal:
      type: fal
      db_profile: dev_postgres # This points to your main adapter
    dev_postgres:
      type: postgres
      host: localhost
      user: myuser
      password: mypassword
      dbname: mydatabase
      schema: public
      port: 5432