iris_data_cleansing:
  target: dev_with_fal
  outputs:
    dev_with_fal:
      type: fal
      db_profile: dev_postgres # This points to your main adapter
    dev_postgres:
      type: postgres
      host: euwest2-postgres-iris-data-cleansing.cfs4s6a8ue2r.eu-west-2.rds.amazonaws.com
      user: postgres
      password: :5t?yqbRMG-sY7pIjy..A0c~.xD]
      dbname: postgres
      schema: data_cleanser
      port: 5432